# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Consumer_pb2 as Consumer__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Consumer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsumerStub(object):
    """The consumer side of the worker<->consumer link. UpdateWorkers hands the
    consumer the full, current set of workers it should connect to (each a
    host:port), replacing whatever local worker list it held before.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateWorkers = channel.unary_unary(
                '/llmconsumer.Consumer/UpdateWorkers',
                request_serializer=Consumer__pb2.UpdateWorkersRequest.SerializeToString,
                response_deserializer=Consumer__pb2.UpdateWorkersReply.FromString,
                _registered_method=True)


class ConsumerServicer(object):
    """The consumer side of the worker<->consumer link. UpdateWorkers hands the
    consumer the full, current set of workers it should connect to (each a
    host:port), replacing whatever local worker list it held before.
    """

    def UpdateWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkers,
                    request_deserializer=Consumer__pb2.UpdateWorkersRequest.FromString,
                    response_serializer=Consumer__pb2.UpdateWorkersReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmconsumer.Consumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmconsumer.Consumer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Consumer(object):
    """The consumer side of the worker<->consumer link. UpdateWorkers hands the
    consumer the full, current set of workers it should connect to (each a
    host:port), replacing whatever local worker list it held before.
    """

    @staticmethod
    def UpdateWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmconsumer.Consumer/UpdateWorkers',
            Consumer__pb2.UpdateWorkersRequest.SerializeToString,
            Consumer__pb2.UpdateWorkersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
