# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Consumer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
# NOTE (coordinator-local copy): the protobuf runtime-version guard emitted
# by protoc 5.28 was stripped so these import under protobuf 3.20.3 — the
# version the etcd3 client pins (protobuf<4). The wire format is unchanged
# (proto3), so this client talks to the 5.28-generated Worker/Consumer
# servers unmodified. Regenerate from grpc/<name>.proto if the contract changes.
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43onsumer.proto\x12\x0bllmconsumer\",\n\x0eWorkerEndpoint\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"D\n\x14UpdateWorkersRequest\x12,\n\x07workers\x18\x01 \x03(\x0b\x32\x1b.llmconsumer.WorkerEndpoint\"/\n\x12UpdateWorkersReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32_\n\x08\x43onsumer\x12S\n\rUpdateWorkers\x12!.llmconsumer.UpdateWorkersRequest\x1a\x1f.llmconsumer.UpdateWorkersReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Consumer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERENDPOINT']._serialized_start=31
  _globals['_WORKERENDPOINT']._serialized_end=75
  _globals['_UPDATEWORKERSREQUEST']._serialized_start=77
  _globals['_UPDATEWORKERSREQUEST']._serialized_end=145
  _globals['_UPDATEWORKERSREPLY']._serialized_start=147
  _globals['_UPDATEWORKERSREPLY']._serialized_end=194
  _globals['_CONSUMER']._serialized_start=196
  _globals['_CONSUMER']._serialized_end=291
# @@protoc_insertion_point(module_scope)
