# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Worker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
# NOTE (coordinator-local copy): the protobuf runtime-version guard emitted
# by protoc 5.28 was stripped so these import under protobuf 3.20.3 — the
# version the etcd3 client pins (protobuf<4). The wire format is unchanged
# (proto3), so this client talks to the 5.28-generated Worker/Consumer
# servers unmodified. Regenerate from grpc/<name>.proto if the contract changes.
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cWorker.proto\x12\tllmworker\"m\n\x10\x41\x64\x64PromptRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\x04\x63hat\x18\x03 \x01(\x03H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x04 \x01(\x03H\x01\x88\x01\x01\x42\x07\n\x05_chatB\n\n\x08_message\"U\n\x0e\x41\x64\x64PromptReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06seq_id\x18\x02 \x01(\x03\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x11\n\tcache_hit\x18\x04 \x01(\x08\"\x0f\n\rStatusRequest\"`\n\x0bStatusReply\x12\x11\n\thas_space\x18\x01 \x01(\x08\x12\x14\n\x0c\x61\x63tive_count\x18\x02 \x01(\x05\x12\x14\n\x0c\x63\x61\x63hed_count\x18\x03 \x01(\x05\x12\x12\n\nmax_active\x18\x04 \x01(\x05\"3\n\x15UpdateConsumerRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"!\n\x13UpdateConsumerReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xe0\x01\n\x06Worker\x12\x43\n\tAddPrompt\x12\x1b.llmworker.AddPromptRequest\x1a\x19.llmworker.AddPromptReply\x12=\n\tGetStatus\x12\x18.llmworker.StatusRequest\x1a\x16.llmworker.StatusReply\x12R\n\x0eUpdateConsumer\x12 .llmworker.UpdateConsumerRequest\x1a\x1e.llmworker.UpdateConsumerReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDPROMPTREQUEST']._serialized_start=27
  _globals['_ADDPROMPTREQUEST']._serialized_end=136
  _globals['_ADDPROMPTREPLY']._serialized_start=138
  _globals['_ADDPROMPTREPLY']._serialized_end=223
  _globals['_STATUSREQUEST']._serialized_start=225
  _globals['_STATUSREQUEST']._serialized_end=240
  _globals['_STATUSREPLY']._serialized_start=242
  _globals['_STATUSREPLY']._serialized_end=338
  _globals['_UPDATECONSUMERREQUEST']._serialized_start=340
  _globals['_UPDATECONSUMERREQUEST']._serialized_end=391
  _globals['_UPDATECONSUMERREPLY']._serialized_start=393
  _globals['_UPDATECONSUMERREPLY']._serialized_end=426
  _globals['_WORKER']._serialized_start=429
  _globals['_WORKER']._serialized_end=653
# @@protoc_insertion_point(module_scope)
