# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Worker_pb2 as Worker__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerStub(object):
    """Simulated LLM inference worker. AddPrompt admits a user message into the
    continuous-batching loop — generated tokens stream to the worker's linked
    redis (stream key tokens:<id>, END token 26 last). GetStatus reports whether
    the worker has space for another prompt.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPrompt = channel.unary_unary(
                '/llmworker.Worker/AddPrompt',
                request_serializer=Worker__pb2.AddPromptRequest.SerializeToString,
                response_deserializer=Worker__pb2.AddPromptReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/llmworker.Worker/GetStatus',
                request_serializer=Worker__pb2.StatusRequest.SerializeToString,
                response_deserializer=Worker__pb2.StatusReply.FromString,
                _registered_method=True)
        self.UpdateConsumer = channel.unary_unary(
                '/llmworker.Worker/UpdateConsumer',
                request_serializer=Worker__pb2.UpdateConsumerRequest.SerializeToString,
                response_deserializer=Worker__pb2.UpdateConsumerReply.FromString,
                _registered_method=True)


class WorkerServicer(object):
    """Simulated LLM inference worker. AddPrompt admits a user message into the
    continuous-batching loop — generated tokens stream to the worker's linked
    redis (stream key tokens:<id>, END token 26 last). GetStatus reports whether
    the worker has space for another prompt.
    """

    def AddPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConsumer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPrompt,
                    request_deserializer=Worker__pb2.AddPromptRequest.FromString,
                    response_serializer=Worker__pb2.AddPromptReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=Worker__pb2.StatusRequest.FromString,
                    response_serializer=Worker__pb2.StatusReply.SerializeToString,
            ),
            'UpdateConsumer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConsumer,
                    request_deserializer=Worker__pb2.UpdateConsumerRequest.FromString,
                    response_serializer=Worker__pb2.UpdateConsumerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmworker.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmworker.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Simulated LLM inference worker. AddPrompt admits a user message into the
    continuous-batching loop — generated tokens stream to the worker's linked
    redis (stream key tokens:<id>, END token 26 last). GetStatus reports whether
    the worker has space for another prompt.
    """

    @staticmethod
    def AddPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmworker.Worker/AddPrompt',
            Worker__pb2.AddPromptRequest.SerializeToString,
            Worker__pb2.AddPromptReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmworker.Worker/GetStatus',
            Worker__pb2.StatusRequest.SerializeToString,
            Worker__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConsumer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmworker.Worker/UpdateConsumer',
            Worker__pb2.UpdateConsumerRequest.SerializeToString,
            Worker__pb2.UpdateConsumerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
