// Vite dev-server plugin: provision a real database into the active system.
//
// POST /api/databases  { system, type, name, entities }
//
// Given a database type and a set of entities, this:
//   1. writes an init script that creates those entities,
//   2. adds the DB service (+ a Prometheus exporter, or native metrics for
//      MinIO) to the system's docker-compose.yml,
//   3. adds a scrape job to the system's prometheus.yml,
//   4. adds a node to the system's manifest.json (no edge — the new DB is NOT
//      auto-wired to any service; that's a deliberate separate step), and
//   5. rebuilds the stack with `docker compose up -d` (NOT ./start.sh, which
//      would kill the very dev server this code runs inside).
//
// The compose/prometheus edits go through the `yaml` Document API so the
// hand-written comments in those files survive. All user input is validated
// against strict whitelists and only ever lands in generated files — never in a
// shell argument.
import fs from 'node:fs'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { parseDocument } from 'yaml'
import { repoRoot, systemsDir, systemDir, isValidSystem, nextNodePosition } from './systems.js'
import { readModelsFile } from './models.js'

const pexec = promisify(execFile)

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

export class HttpError extends Error {
  constructor(status, message) {
    super(message)
    this.statusCode = status
  }
}
export const bad = (msg) => new HttpError(400, msg)

const DB_NAME_RE = /^[a-z][a-z0-9-]*$/ // also a valid compose service name
const IDENT_RE = /^[a-zA-Z_][a-zA-Z0-9_]*$/ // SQL/Mongo identifier-ish
const BUCKET_RE = /^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/ // S3-ish bucket name

const SQL_FIELD_TYPES = new Set([
  'text', 'varchar', 'integer', 'bigint', 'numeric', 'boolean',
  'timestamp', 'timestamptz', 'date', 'uuid', 'jsonb', 'serial', 'bigserial',
])
const MONGO_FIELD_TYPES = new Set([
  'string', 'number', 'boolean', 'date', 'objectId', 'object', 'array',
])

// Health rule shared by every DB node: red when the target is down, green up.
export const HEALTH_RULES = [
  { color: 'red', when: 'value < 1' },
  { color: 'green', when: 'value >= 1' },
]

export function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    let data = ''
    req.on('data', (chunk) => {
      data += chunk
      if (data.length > 1_000_000) reject(bad('request body too large'))
    })
    req.on('end', () => {
      if (!data) return resolve({})
      try {
        resolve(JSON.parse(data))
      } catch {
        reject(bad('invalid JSON body'))
      }
    })
    req.on('error', reject)
  })
}

// ---------------------------------------------------------------------------
// Per-type templates
//
// Each builder returns everything needed to splice one database into a system:
//   services  — map of compose service name -> service definition object
//   scrapeJob — a prometheus scrape_configs entry
//   metrics   — manifest node metrics[]
//   health    — manifest node health{}
//   nodeType  — manifest node `type` (shown on the diagram)
//   files     — init scripts to write under systems/<id>/<name>/
// `name` is the DB node id / primary service name; `job` (== name) labels the
// scrape so multiple DBs of the same engine stay distinguishable in PromQL.
// ---------------------------------------------------------------------------

function sqlColumns(entity) {
  const fields = entity.fields || []
  if (fields.length === 0) return ['  "id" bigserial primary key']
  return fields.map((f) => `  "${f.name}" ${f.type}`)
}

function buildPostgres({ name, dbName, entities }) {
  const tables = entities
    .map((e) => `CREATE TABLE IF NOT EXISTS "${e.name}" (\n${sqlColumns(e).join(',\n')}\n);`)
    .join('\n\n')
  const initSql = `-- Generated by "Add database". Runs once on first init of ${name}.\n${tables}\n`

  return {
    nodeType: 'postgres',
    services: {
      [name]: {
        image: 'postgres:16-alpine',
        environment: {
          POSTGRES_USER: 'sandbox',
          POSTGRES_PASSWORD: 'sandbox',
          POSTGRES_DB: dbName,
        },
        volumes: [`./${name}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro`],
      },
      [`${name}-exporter`]: {
        image: 'quay.io/prometheuscommunity/postgres-exporter:v0.16.0',
        environment: {
          DATA_SOURCE_NAME: `postgresql://sandbox:sandbox@${name}:5432/${dbName}?sslmode=disable`,
        },
        depends_on: [name],
      },
    },
    scrapeJob: { job_name: name, static_configs: [{ targets: [`${name}-exporter:9187`] }] },
    metrics: [
      { label: 'connections', query: `sum(pg_stat_database_numbackends{job="${name}"})`, unit: '' },
      { label: 'commits/s', query: `sum(rate(pg_stat_database_xact_commit{job="${name}"}[1m]))`, unit: '/s' },
      { label: 'rows fetch/s', query: `sum(rate(pg_stat_database_tup_fetched{job="${name}"}[1m]))`, unit: '/s' },
    ],
    health: { query: `pg_up{job="${name}"}`, rules: HEALTH_RULES },
    files: [{ rel: 'init.sql', content: initSql }],
  }
}

function mongoSampleValue(type) {
  switch (type) {
    case 'number': return 0
    case 'boolean': return false
    case 'date': return 'new Date()'
    case 'objectId': return 'new ObjectId()'
    case 'object': return '{}'
    case 'array': return '[]'
    default: return '"sample"'
  }
}

function buildMongo({ name, dbName, entities }) {
  const lines = [`// Generated by "Add database". Runs once on first init of ${name}.`]
  for (const e of entities) {
    lines.push(`db.createCollection("${e.name}");`)
    const fields = e.fields || []
    if (fields.length) {
      const doc = fields.map((f) => `  "${f.name}": ${mongoSampleValue(f.type)}`).join(',\n')
      lines.push(`db.${e.name}.insertOne({\n${doc}\n});`)
    }
  }
  const initJs = lines.join('\n') + '\n'

  return {
    nodeType: 'mongodb',
    services: {
      [name]: {
        image: 'mongo:7',
        environment: { MONGO_INITDB_DATABASE: dbName },
        volumes: [`./${name}/init.js:/docker-entrypoint-initdb.d/init.js:ro`],
      },
      [`${name}-exporter`]: {
        image: 'percona/mongodb_exporter:0.40',
        command: [`--mongodb.uri=mongodb://${name}:27017`, '--collect-all', '--compatible-mode'],
        depends_on: [name],
      },
    },
    scrapeJob: { job_name: name, static_configs: [{ targets: [`${name}-exporter:9216`] }] },
    metrics: [
      { label: 'connections', query: `sum(mongodb_ss_connections{job="${name}",conn_type="current"})`, unit: '' },
      { label: 'ops/s', query: `sum(rate(mongodb_ss_opcounters{job="${name}"}[1m]))`, unit: '/s' },
    ],
    health: { query: `mongodb_up{job="${name}"}`, rules: HEALTH_RULES },
    files: [{ rel: 'init.js', content: initJs }],
  }
}

function buildRedis({ name, entities }) {
  // Redis has no init-dir mechanism, so a one-shot sidecar seeds one sample key
  // per namespace once the server answers PING.
  const seed = [
    'set -e',
    `until redis-cli -h ${name} ping | grep -q PONG; do sleep 1; done`,
    ...entities.map((e) => `redis-cli -h ${name} SET "${e.name}:sample" "seed"`),
  ].join('\n')

  return {
    nodeType: 'redis',
    services: {
      [name]: { image: 'redis:7-alpine' },
      [`${name}-init`]: {
        image: 'redis:7-alpine',
        depends_on: [name],
        restart: 'no',
        entrypoint: ['sh', '-c', seed],
      },
      [`${name}-exporter`]: {
        image: 'oliver006/redis_exporter:v1.62.0',
        environment: { REDIS_ADDR: `redis://${name}:6379` },
        depends_on: [name],
      },
    },
    scrapeJob: { job_name: name, static_configs: [{ targets: [`${name}-exporter:9121`] }] },
    metrics: [
      { label: 'clients', query: `redis_connected_clients{job="${name}"}`, unit: '' },
      { label: 'ops/s', query: `sum(rate(redis_commands_processed_total{job="${name}"}[1m]))`, unit: '/s' },
      { label: 'keys', query: `sum(redis_db_keys{job="${name}"})`, unit: '' },
    ],
    health: { query: `redis_up{job="${name}"}`, rules: HEALTH_RULES },
    files: [],
  }
}

function buildBlob({ name, entities }) {
  // MinIO exposes Prometheus metrics natively (no exporter); a one-shot `mc`
  // sidecar creates the buckets. Auth set to public so Prometheus can scrape.
  const mc = [
    'set -e',
    `until mc alias set local http://${name}:9000 sandbox sandbox123; do sleep 1; done`,
    ...entities.map((e) => `mc mb -p local/${e.name} || true`),
  ].join('\n')

  return {
    nodeType: 'object-store',
    services: {
      [name]: {
        image: 'minio/minio:latest',
        command: ['server', '/data', '--console-address', ':9001'],
        environment: {
          MINIO_ROOT_USER: 'sandbox',
          MINIO_ROOT_PASSWORD: 'sandbox123',
          MINIO_PROMETHEUS_AUTH_TYPE: 'public',
        },
      },
      [`${name}-init`]: {
        image: 'minio/mc:latest',
        depends_on: [name],
        restart: 'no',
        entrypoint: ['sh', '-c', mc],
      },
    },
    scrapeJob: {
      job_name: name,
      metrics_path: '/minio/v2/metrics/cluster',
      static_configs: [{ targets: [`${name}:9000`] }],
    },
    metrics: [
      { label: 'capacity', query: `sum(minio_cluster_capacity_usable_total_bytes{job="${name}"})`, unit: 'GB', scale: 1e-9 },
      { label: 'S3 req/s', query: `sum(rate(minio_s3_requests_total{job="${name}"}[1m]))`, unit: '/s' },
    ],
    health: { query: `up{job="${name}"}`, rules: HEALTH_RULES },
    files: [],
  }
}

const TYPES = {
  postgres: { label: 'PostgreSQL', fieldTypes: SQL_FIELD_TYPES, entityRe: IDENT_RE, build: buildPostgres },
  mongodb: { label: 'MongoDB', fieldTypes: MONGO_FIELD_TYPES, entityRe: IDENT_RE, build: buildMongo },
  redis: { label: 'Redis', fieldTypes: null, entityRe: IDENT_RE, build: buildRedis },
  blob: { label: 'Blob (S3)', fieldTypes: null, entityRe: BUCKET_RE, build: buildBlob },
}

// ---------------------------------------------------------------------------
// Validation of the request body
// ---------------------------------------------------------------------------

function validate(body) {
  const { system, type, name } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const spec = TYPES[type]
  if (!spec) throw bad(`unknown database type "${type}"`)
  if (typeof name !== 'string' || !DB_NAME_RE.test(name) || name.length > 40) {
    throw bad('name must be lowercase letters, digits and hyphens (start with a letter)')
  }

  const manifest = JSON.parse(fs.readFileSync(path.join(systemDir(system), 'manifest.json'), 'utf8'))
  if (manifest.nodes.some((n) => n.id === name)) {
    throw bad(`a node named "${name}" already exists in this system`)
  }
  if (fs.existsSync(path.join(systemDir(system), name))) {
    throw bad(`systems/${system}/${name}/ already exists`)
  }

  // Model mode (postgres/mongodb only): the schema is authored from selected model-bank
  // models by a Claude session, so we provision an EMPTY container here (no entities) and
  // record the chosen models on the node. Entities are not used in this mode.
  const models = Array.isArray(body.models) ? body.models : null
  if (models && models.length) {
    if (type !== 'postgres' && type !== 'mongodb') {
      throw bad('selecting models is only supported for postgres and mongodb')
    }
    const bank = new Set(readModelsFile(system).models.map((m) => m.name))
    for (const n of models) {
      if (typeof n !== 'string' || !bank.has(n)) throw bad(`unknown model "${n}"`)
    }
    return { system, type, spec, name, manifest, entities: [], models }
  }

  const rawEntities = Array.isArray(body.entities) ? body.entities : []
  if (rawEntities.length === 0) throw bad('add at least one entity')
  const entities = rawEntities.map((e) => {
    if (!e || !spec.entityRe.test(e.name || '')) {
      throw bad(`invalid entity name "${e && e.name}" for ${spec.label}`)
    }
    const fields = (spec.fieldTypes && Array.isArray(e.fields) ? e.fields : []).map((f) => {
      if (!IDENT_RE.test(f.name || '')) throw bad(`invalid field name "${f && f.name}"`)
      if (!spec.fieldTypes.has(f.type)) throw bad(`invalid field type "${f && f.type}"`)
      return { name: f.name, type: f.type }
    })
    return { name: e.name, fields }
  })

  return { system, type, spec, name, manifest, entities, models: null }
}

// ---------------------------------------------------------------------------
// File mutations
// ---------------------------------------------------------------------------

// Append a service to docker-compose.yml, preserving its comments.
export function addComposeServices(system, services, name, label, by = 'Add database') {
  const file = path.join(systemDir(system), 'docker-compose.yml')
  const doc = parseDocument(fs.readFileSync(file, 'utf8'))
  let first = true
  for (const [svc, def] of Object.entries(services)) {
    const node = doc.createNode(def)
    if (first) {
      node.commentBefore = ` ${label} "${name}" — added by ${by}`
      first = false
    }
    doc.setIn(['services', svc], node)
  }
  fs.writeFileSync(file, doc.toString())
}

// Append a scrape job to prometheus.yml, preserving its comments.
export function addScrapeJob(system, scrapeJob, name, by = 'Add database', kind = 'Database') {
  const file = path.join(systemDir(system), 'prometheus', 'prometheus.yml')
  const doc = parseDocument(fs.readFileSync(file, 'utf8'))
  const node = doc.createNode(scrapeJob)
  node.commentBefore = ` ${kind} "${name}" — added by ${by}`
  doc.addIn(['scrape_configs'], node)
  fs.writeFileSync(file, doc.toString())
}

// Append the node to manifest.json (no edge). The node's label is just its name —
// the engine is already shown by the node `type` in the header's upper-right corner,
// so prefixing the label with it (e.g. "PostgreSQL · ") would duplicate it.
function addManifestNode(system, manifest, built, name, schemaModels) {
  const node = {
    id: name,
    label: name,
    type: built.nodeType,
    origin: 'create-database',
    position: nextNodePosition(manifest),
    metrics: built.metrics,
    health: built.health,
  }
  // Model mode records which bank models were turned into tables/collections, so the
  // Schema tab can show them and additive updates can extend the set.
  if (schemaModels && schemaModels.length) node.schemaModels = schemaModels
  manifest.nodes.push(node)
  fs.writeFileSync(
    path.join(systemDir(system), 'manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n',
  )
  return node
}

async function rebuild(system) {
  // Escape hatch for tests/CI: validate the file generation without spending a
  // minute pulling images and starting containers.
  if (process.env.CREATE_DB_SKIP_REBUILD === '1') return '(rebuild skipped)'

  const compose = path.join(systemsDir, system, 'docker-compose.yml')
  const opts = { cwd: repoRoot, timeout: 300_000, maxBuffer: 16 * 1024 * 1024 }
  let log = ''
  try {
    // up -d (no --build) leaves existing services running and only creates the
    // new ones. Prometheus's service definition is unchanged, so its mounted
    // config won't reload on `up` — restart it to pick up the new scrape job.
    const up = await pexec('docker', ['compose', '-f', compose, 'up', '-d'], opts)
    log += up.stdout + up.stderr
    const r = await pexec('docker', ['compose', '-f', compose, 'restart', 'prometheus'], opts)
    log += r.stdout + r.stderr
  } catch (err) {
    const detail = `${err.stdout || ''}${err.stderr || ''}` || err.message
    throw new HttpError(500, `docker compose failed:\n${detail}`)
  }
  return log
}

export async function handleCreate(body) {
  const { system, spec, name, manifest, entities, models } = validate(body)
  const dbName = name.replace(/-/g, '_')
  const built = spec.build({ name, dbName, entities })

  // 1. init scripts (in model mode `entities` is empty, so this is a header-only
  //    placeholder — the launched Claude session writes the real schema).
  const dir = systemDir(system)
  if (built.files.length) {
    fs.mkdirSync(path.join(dir, name), { recursive: true })
    for (const f of built.files) {
      fs.writeFileSync(path.join(dir, name, f.rel), f.content)
    }
  }

  // 2-4. compose, prometheus, manifest
  addComposeServices(system, built.services, name, spec.label)
  addScrapeJob(system, built.scrapeJob, name)
  const node = addManifestNode(system, manifest, built, name, models)

  // 5. rebuild (frontend-safe)
  const log = await rebuild(system)
  return { ok: true, node, log }
}

// POST /api/db-models — record which bank models an EXISTING postgres/mongodb database's
// schema is built from. No rebuild: the launched Claude session applies the schema to the
// live container. The set is merged (additive) since updates add tables/collections.
export function handleSetModels(body) {
  const { system, id } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const manifestPath = path.join(systemDir(system), 'manifest.json')
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  const node = manifest.nodes.find((n) => n.id === id)
  if (!node || node.origin !== 'create-database') {
    throw bad(`"${id}" is not a database in this system`)
  }
  if (node.replicaOf) throw bad('cannot author schema on a read replica')
  if (node.type !== 'postgres' && node.type !== 'mongodb') {
    throw bad('selecting models is only supported for postgres and mongodb')
  }
  const models = Array.isArray(body.models) ? body.models : []
  if (!models.length) throw bad('select at least one model')
  const bank = new Set(readModelsFile(system).models.map((m) => m.name))
  for (const n of models) {
    if (typeof n !== 'string' || !bank.has(n)) throw bad(`unknown model "${n}"`)
  }
  node.schemaModels = [...new Set([...(node.schemaModels || []), ...models])]
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n')
  return { ok: true, node }
}

export default function createDatabase() {
  return {
    name: 'create-database',
    configureServer(server) {
      const send = (res, code, body) => {
        res.statusCode = code
        res.setHeader('Content-Type', 'application/json')
        res.end(JSON.stringify(body))
      }

      server.middlewares.use('/api/databases', async (req, res, next) => {
        if (req.method !== 'POST') return next()
        try {
          const result = await handleCreate(await readJsonBody(req))
          send(res, 200, result)
        } catch (err) {
          send(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })

      // Record which bank models an existing postgres/mongodb db's schema is built from
      // (the frontend then launches a Claude session to apply the schema).
      server.middlewares.use('/api/db-models', async (req, res, next) => {
        if (req.method !== 'POST') return next()
        try {
          const result = handleSetModels(await readJsonBody(req))
          send(res, 200, result)
        } catch (err) {
          send(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })
    },
  }
}
