// Vite dev-server plugin: seed a database with fixture rows that AUTO-REPLAY.
//
//   GET  /api/db-seed?system=&id=    -> { ok, type, label, entities, seeds }
//   POST /api/db-seed                { system, id, table, row }    add one entry
//   POST /api/db-seed-remove         { system, id, table, index }  remove one entry
//   POST /api/db-seed-apply          { system, id }                re-apply all (idempotent)
//
// Entries persist in systems/<id>/<db>/seeds.json — the source of truth. On every
// change we (1) regenerate an IDEMPOTENT seed artifact (postgres `seed.sql` /
// mongodb `seed.js`), (2) apply it to the live container via `docker compose exec`,
// and (3) ensure that artifact is mounted into the db's init dir AFTER the schema
// script, so a fresh `down -v` rebuild reproduces the data automatically. The
// sandbox-database skill re-runs the same artifact after a schema migration. So the
// rows survive migrations, test wipes (Re-seed now), and from-scratch rebuilds.
//
// Postgres + MongoDB only (the table/collection engines with field-shaped schemas).
// Table and field names are whitelisted against the LIVE introspected schema, never
// the request; values are escaped before they land in the generated SQL/JS; docker
// runs via execFile arg arrays (composeExec), never a shell string.
import fs from 'node:fs'
import path from 'node:path'
import { parseDocument } from 'yaml'
import { systemDir, isValidSystem } from './systems.js'
import { composeExec, getSchema } from './dbschema.js'
import { readJsonBody, bad } from './databases.js'

const SEED_ENGINES = new Set(['postgres', 'mongodb', 'cassandra', 'dynamodb'])

// Resolve + validate a request to a real, seedable database node.
function dbNode(system, id) {
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const manifest = JSON.parse(fs.readFileSync(path.join(systemDir(system), 'manifest.json'), 'utf8'))
  const node = (manifest.nodes || []).find((n) => n.id === id)
  if (!node || node.origin !== 'create-database') throw bad(`"${id}" is not a database in this system`)
  if (node.replicaOf) throw bad('cannot seed a read replica')
  if (!SEED_ENGINES.has(node.type)) throw bad(`seeding is not supported for ${node.type}`)
  return node
}

const dbName = (id) => id.replace(/-/g, '_')
const seedsPath = (system, id) => path.join(systemDir(system), id, 'seeds.json')

function readSeeds(system, id) {
  try {
    const raw = JSON.parse(fs.readFileSync(seedsPath(system, id), 'utf8'))
    const tables = Array.isArray(raw.tables) ? raw.tables : []
    return {
      tables: tables
        .filter((t) => t && typeof t.table === 'string')
        .map((t) => ({ table: t.table, rows: Array.isArray(t.rows) ? t.rows : [] })),
    }
  } catch {
    return { tables: [] }
  }
}

function writeSeeds(system, id, seeds) {
  const dir = path.join(systemDir(system), id)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(seedsPath(system, id), JSON.stringify(seeds, null, 2) + '\n')
}

const totalRows = (seeds) => seeds.tables.reduce((n, t) => n + t.rows.length, 0)

// --- artifact generation (idempotent) ---------------------------------------

const sqlLit = (v) => `'${String(v).replace(/'/g, "''")}'`

function pgInsert(table, row) {
  const cols = Object.keys(row)
  const colList = cols.map((c) => `"${c}"`).join(', ')
  const vals = cols.map((c) => sqlLit(row[c])).join(', ')
  // ON CONFLICT DO NOTHING (no target) swallows any PK/unique violation, so the
  // statement is safe to re-run — model-backed tables always have a primary key.
  return `INSERT INTO "${table}" (${colList}) VALUES (${vals}) ON CONFLICT DO NOTHING;`
}

function buildPgSeed(seeds) {
  const lines = ['-- Generated by the Seed tab. Idempotent — re-applied live, after migrations, and on rebuild.']
  for (const t of seeds.tables) for (const r of t.rows) lines.push(pgInsert(t.table, r))
  return lines.join('\n') + '\n'
}

// Render a stored (string) value as a JS literal, typed by the live schema where known.
function mongoVal(v, type) {
  if (type === 'Number') {
    const n = Number(v)
    return Number.isFinite(n) ? String(n) : JSON.stringify(String(v))
  }
  if (type === 'Boolean') return v === true || v === 'true' ? 'true' : 'false'
  if (type === 'Date') return `new Date(${JSON.stringify(String(v))})`
  return JSON.stringify(typeof v === 'string' ? v : String(v))
}

function mongoStatement(table, row, types) {
  const t = types || {}
  const pairs = Object.keys(row)
    .map((k) => `${JSON.stringify(k)}: ${mongoVal(row[k], t[k])}`)
    .join(', ')
  const keyField = 'id' in row ? 'id' : '_id' in row ? '_id' : null
  if (keyField) {
    const filter = `{ ${JSON.stringify(keyField)}: ${mongoVal(row[keyField], t[keyField])} }`
    // Idempotent upsert keyed on the row's id/_id.
    return `db[${JSON.stringify(table)}].updateOne(${filter}, { $setOnInsert: { ${pairs} } }, { upsert: true });`
  }
  return `db[${JSON.stringify(table)}].insertOne({ ${pairs} });`
}

function buildMongoSeed(seeds, typeMap) {
  const lines = ['// Generated by the Seed tab. Idempotent — re-applied live, after migrations, and on rebuild.']
  for (const t of seeds.tables) for (const r of t.rows) lines.push(mongoStatement(t.table, r, typeMap[t.table]))
  return lines.join('\n') + '\n'
}

// Map { tableName: { fieldName: jsType } } from a live schema (for mongo typing).
function typeMapOf(schema) {
  const map = {}
  for (const e of schema.entities || []) map[e.name] = Object.fromEntries((e.fields || []).map((f) => [f.name, f.type]))
  return map
}

// --- Cassandra (CQL) ---------------------------------------------------------

// The introspected type carries the column KIND in parens (e.g. `text(partition_key)`);
// the base CQL type is everything before it.
const cqlBaseType = (type) => String(type || '').replace(/\(.*/, '').trim()
const CQL_NUMERIC = new Set(['int', 'bigint', 'smallint', 'tinyint', 'varint', 'float', 'double', 'decimal', 'counter'])

function cqlLit(v, type) {
  const base = cqlBaseType(type)
  if (base === 'boolean') return v === true || v === 'true' ? 'true' : 'false'
  if (CQL_NUMERIC.has(base)) {
    const n = Number(v)
    return Number.isFinite(n) ? String(n) : 'null'
  }
  if (base === 'uuid' || base === 'timeuuid') return String(v) // CQL uuid literal is unquoted
  return `'${String(v).replace(/'/g, "''")}'`
}

// A plain INSERT is an idempotent upsert by primary key in Cassandra (no LWT needed).
function cqlInsert(ks, table, row, types) {
  const cols = Object.keys(row)
  const colList = cols.join(', ')
  const vals = cols.map((c) => cqlLit(row[c], (types || {})[c])).join(', ')
  return `INSERT INTO ${ks}.${table} (${colList}) VALUES (${vals});`
}

function buildCqlSeed(seeds, ks, typeMap) {
  const lines = ['-- Generated by the Seed tab. Idempotent — INSERT is an upsert by primary key.']
  for (const t of seeds.tables) for (const r of t.rows) lines.push(cqlInsert(ks, t.table, r, typeMap[t.table]))
  return lines.join('\n') + '\n'
}

async function applyCql(system, id, cql) {
  if (!cql.trim()) return
  // cqlsh runs inside the DB container (defaults to its local node); statements are
  // keyspace-qualified, so no USE needed.
  await composeExec(system, id, { envFlags: [], argv: ['cqlsh', '-e', cql] })
}

// --- DynamoDB ----------------------------------------------------------------

// DynamoDB is schemaless beyond its keys; introspection reports each key attribute's
// type in parens (e.g. `id:HASH(S)` -> type string `HASH(S)`). Map { table: { attr: 'S'|'N'|'B' } }.
function ddbKeyTypes(schema) {
  const out = {}
  for (const e of schema?.entities || []) {
    const m = {}
    for (const f of e.fields || []) {
      const mm = /\(([SNB])\)/.exec(f.type || '')
      if (mm) m[f.name] = mm[1]
    }
    out[e.name] = m
  }
  return out
}

// Render a seed row as a DynamoDB item. Only KEY attributes carry a declared type; a
// numeric/binary key is typed accordingly, everything else is a string (S) attribute.
function ddbItem(row, keyTypes) {
  const item = {}
  for (const [k, v] of Object.entries(row)) {
    const t = (keyTypes || {})[k]
    item[k] = t === 'N' ? { N: String(Number(v)) } : t === 'B' ? { B: String(v) } : { S: String(v) }
  }
  return item
}

function ddbItemsArr(seeds, schema) {
  const kt = ddbKeyTypes(schema)
  const out = []
  for (const t of seeds.tables) for (const r of t.rows) out.push({ table: t.table, item: ddbItem(r, kt[t.table]) })
  return out
}

// Wrap a value for a single-quoted POSIX shell context.
const shq = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`

function buildDdbSeedSh(seeds, schema, id) {
  const kt = ddbKeyTypes(schema)
  const lines = ['#!/bin/sh', '# Generated by the Seed tab. Idempotent (put-item overwrites by key).']
  for (const t of seeds.tables) {
    for (const r of t.rows) {
      const json = JSON.stringify(ddbItem(r, kt[t.table]))
      lines.push(`aws dynamodb put-item --endpoint-url http://${id}:8000 --table-name ${shq(t.table)} --item ${shq(json)} || true`)
    }
  }
  return lines.join('\n') + '\n'
}

// Live apply/delete run boto3 in the exporter sidecar (it has boto3 + the DDB endpoint;
// the DB container has no client). All input travels via env, never a shell string.
const DDB_PUT_PY =
  'import os, json, boto3\n' +
  'c = boto3.client("dynamodb", endpoint_url=os.environ["DDB_ENDPOINT"], region_name="us-east-1", aws_access_key_id="sandbox", aws_secret_access_key="sandbox")\n' +
  'for it in json.loads(os.environ["ITEMS"]):\n' +
  '    c.put_item(TableName=it["table"], Item=it["item"])\n'
const DDB_DEL_PY =
  'import os, json, boto3\n' +
  'c = boto3.client("dynamodb", endpoint_url=os.environ["DDB_ENDPOINT"], region_name="us-east-1", aws_access_key_id="sandbox", aws_secret_access_key="sandbox")\n' +
  'c.delete_item(TableName=os.environ["TBL"], Key=json.loads(os.environ["KEY"]))\n'

async function ddbExec(system, id, script, env) {
  await composeExec(system, `${id}-exporter`, {
    envFlags: Object.entries(env || {}).flatMap(([k, v]) => ['-e', `${k}=${v}`]),
    argv: ['python', '-c', script],
  })
}

const applyDdb = (system, id, items) =>
  items.length ? ddbExec(system, id, DDB_PUT_PY, { ITEMS: JSON.stringify(items) }) : Promise.resolve()

// Regenerate the on-disk seed artifact from seeds.json (+ live schema for mongo types).
function regenerate(system, id, node, schema) {
  const seeds = readSeeds(system, id)
  const dir = path.join(systemDir(system), id)
  fs.mkdirSync(dir, { recursive: true })
  const safe = schema || { entities: [] }
  if (node.type === 'postgres') fs.writeFileSync(path.join(dir, 'seed.sql'), buildPgSeed(seeds))
  else if (node.type === 'mongodb') fs.writeFileSync(path.join(dir, 'seed.js'), buildMongoSeed(seeds, typeMapOf(safe)))
  else if (node.type === 'cassandra') fs.writeFileSync(path.join(dir, 'seed.cql'), buildCqlSeed(seeds, dbName(id), typeMapOf(safe)))
  else if (node.type === 'dynamodb') fs.writeFileSync(path.join(dir, 'seed.sh'), buildDdbSeedSh(seeds, safe, id))
}

// --- live apply / delete -----------------------------------------------------

async function applyPgSql(system, id, sql) {
  if (!sql.trim()) return
  await composeExec(system, id, {
    envFlags: ['-e', 'PGPASSWORD=sandbox'],
    argv: ['psql', '-U', 'sandbox', '-d', dbName(id), '-w', '-v', 'ON_ERROR_STOP=1', '-c', sql],
  })
}

async function applyMongoJs(system, id, js) {
  if (!js.trim()) return
  await composeExec(system, id, { envFlags: [], argv: ['mongosh', dbName(id), '--quiet', '--eval', js] })
}

async function applyAll(system, id, node, schema) {
  const seeds = readSeeds(system, id)
  if (node.type === 'postgres') await applyPgSql(system, id, buildPgSeed(seeds))
  else if (node.type === 'mongodb') await applyMongoJs(system, id, buildMongoSeed(seeds, typeMapOf(schema)))
  else if (node.type === 'cassandra') await applyCql(system, id, buildCqlSeed(seeds, dbName(id), typeMapOf(schema)))
  else if (node.type === 'dynamodb') await applyDdb(system, id, ddbItemsArr(seeds, schema))
}

async function deleteLiveRow(system, id, node, table, row, types) {
  const keys = Object.keys(row)
  if (!keys.length) return
  const t = types || {}
  if (node.type === 'postgres') {
    const where = keys.map((c) => `"${c}" = ${sqlLit(row[c])}`).join(' AND ')
    await applyPgSql(system, id, `DELETE FROM "${table}" WHERE ${where};`)
  } else if (node.type === 'cassandra') {
    // Delete by the columns we have (the primary key ones matter); values typed via CQL.
    const where = keys.map((c) => `${c} = ${cqlLit(row[c], t[c])}`).join(' AND ')
    await applyCql(system, id, `DELETE FROM ${dbName(id)}.${table} WHERE ${where};`)
  } else if (node.type === 'dynamodb') {
    // delete_item needs the key attrs only (typed from the introspected schema, e.g. `HASH(S)`).
    const key = {}
    for (const [k, v] of Object.entries(row)) {
      const m = /\(([SNB])\)/.exec(t[k] || '')
      if (m) key[k] = m[1] === 'N' ? { N: String(Number(v)) } : { S: String(v) }
    }
    if (!Object.keys(key).length) return
    await ddbExec(system, id, DDB_DEL_PY, { TBL: table, KEY: JSON.stringify(key) })
  } else {
    const field = 'id' in row ? 'id' : '_id' in row ? '_id' : null
    const filter = field
      ? `{ ${JSON.stringify(field)}: ${mongoVal(row[field], t[field])} }`
      : `{ ${keys.map((k) => `${JSON.stringify(k)}: ${mongoVal(row[k], t[k])}`).join(', ')} }`
    await applyMongoJs(system, id, `db[${JSON.stringify(table)}].deleteOne(${filter});`)
  }
}

// --- compose mount (fresh-rebuild replay) ------------------------------------

// Where each engine's seed artifact gets mounted for from-scratch rebuild replay.
// postgres/mongodb drop it into the DB's init dir (runs after the schema script).
// cassandra/dynamodb have no init dir, so it mounts into the `-init` sidecar, whose
// script runs it after the schema (see buildCassandra/buildDynamo in databases.js).
const SEED_MOUNTS = {
  postgres: { file: 'seed.sql', service: (id) => id, dest: (f) => `/docker-entrypoint-initdb.d/${f}` },
  mongodb: { file: 'seed.js', service: (id) => id, dest: (f) => `/docker-entrypoint-initdb.d/${f}` },
  cassandra: { file: 'seed.cql', service: (id) => `${id}-init`, dest: () => '/seed.cql' },
  dynamodb: { file: 'seed.sh', service: (id) => `${id}-init`, dest: () => '/seed.sh' },
}

// Add the seed mount so a from-scratch (`down -v` + up) rebuild runs schema then seed.
// Idempotent: adds the mount only if absent and only edits the compose file (no recreate
// here — the running container's data is kept correct by the live apply; the mount takes
// effect on the next rebuild).
function ensureSeedMount(system, id, node) {
  const spec = SEED_MOUNTS[node.type]
  if (!spec) return false
  const mount = `./${id}/${spec.file}:${spec.dest(spec.file)}:ro`
  const file = path.join(systemDir(system), 'docker-compose.yml')
  const doc = parseDocument(fs.readFileSync(file, 'utf8'))
  const volsPath = ['services', spec.service(id), 'volumes']
  const node_ = doc.getIn(volsPath)
  const existing = node_ && typeof node_.toJSON === 'function' ? node_.toJSON() : Array.isArray(node_) ? node_ : []
  if (existing.includes(mount)) return false
  doc.addIn(volsPath, doc.createNode(mount))
  fs.writeFileSync(file, doc.toString())
  return true
}

// --- request handlers --------------------------------------------------------

async function handleGet(system, id) {
  dbNode(system, id)
  const schema = await getSchema(system, id) // throws 502 if the container is down
  return { ok: true, type: schema.type, label: schema.label, entities: schema.entities, seeds: readSeeds(system, id) }
}

async function handleAdd(body) {
  const { system, id } = body
  const node = dbNode(system, id)
  const table = String(body.table || '')
  const row = body.row && typeof body.row === 'object' && !Array.isArray(body.row) ? body.row : null
  if (!row) throw bad('row must be an object')

  const schema = await getSchema(system, id)
  const entity = schema.entities.find((e) => e.name === table)
  if (!entity) throw bad(`unknown ${node.type === 'mongodb' ? 'collection' : 'table'} "${table}"`)
  const allowed = new Set(entity.fields.map((f) => f.name))
  // DynamoDB is schemaless beyond its keys — its introspected "fields" are only the key
  // attributes, so don't whitelist against them; accept any attribute identifier.
  const schemaless = node.type === 'dynamodb'

  // Whitelist field names against the live schema; drop blanks so DB defaults apply.
  // (An empty mongo collection / a schemaless store has no fixed fields — accept any identifier.)
  const clean = {}
  for (const [k, v] of Object.entries(row)) {
    if (v === '' || v === null || v === undefined) continue
    if (!schemaless && allowed.size && !allowed.has(k)) throw bad(`unknown field "${k}" for "${table}"`)
    if ((schemaless || !allowed.size) && !/^[A-Za-z_][A-Za-z0-9_]*$/.test(k)) throw bad(`invalid field name "${k}"`)
    clean[k] = typeof v === 'string' ? v : String(v)
  }
  if (!Object.keys(clean).length) throw bad('enter at least one field value')

  // Apply live FIRST (the container is up) so a row that violates an FK/constraint/key
  // surfaces an error and is never persisted.
  if (node.type === 'postgres') await applyPgSql(system, id, pgInsert(table, clean))
  else if (node.type === 'mongodb') await applyMongoJs(system, id, mongoStatement(table, clean, typeMapOf(schema)[table]))
  else if (node.type === 'cassandra') await applyCql(system, id, cqlInsert(dbName(id), table, clean, typeMapOf(schema)[table]))
  else if (node.type === 'dynamodb') await applyDdb(system, id, [{ table, item: ddbItem(clean, ddbKeyTypes(schema)[table]) }])

  const seeds = readSeeds(system, id)
  let group = seeds.tables.find((t) => t.table === table)
  if (!group) {
    group = { table, rows: [] }
    seeds.tables.push(group)
  }
  group.rows.push(clean)
  writeSeeds(system, id, seeds)
  regenerate(system, id, node, schema)
  ensureSeedMount(system, id, node)
  return { ok: true, seeds }
}

async function handleRemove(body) {
  const { system, id } = body
  const node = dbNode(system, id)
  const table = String(body.table || '')
  const index = Number(body.index)
  const seeds = readSeeds(system, id)
  const group = seeds.tables.find((t) => t.table === table)
  if (!group || !Number.isInteger(index) || index < 0 || index >= group.rows.length) {
    throw bad('no such seed entry')
  }
  const [removed] = group.rows.splice(index, 1)
  if (!group.rows.length) seeds.tables = seeds.tables.filter((t) => t !== group)
  writeSeeds(system, id, seeds)

  let schema = null
  try {
    schema = await getSchema(system, id)
  } catch {
    /* container may be down — still update the registry + artifact */
  }
  regenerate(system, id, node, schema)
  // Best-effort: drop the matching live row so the DB and registry stay consistent.
  try {
    await deleteLiveRow(system, id, node, table, removed, typeMapOf(schema || { entities: [] })[table])
  } catch {
    /* leave the live row if the delete fails (e.g. referenced by an FK) */
  }
  return { ok: true, seeds }
}

async function handleApply(body) {
  const { system, id } = body
  const node = dbNode(system, id)
  const schema = await getSchema(system, id)
  regenerate(system, id, node, schema)
  await applyAll(system, id, node, schema)
  ensureSeedMount(system, id, node)
  return { ok: true, seeds: readSeeds(system, id), applied: totalRows(readSeeds(system, id)) }
}

export default function dbSeed() {
  return {
    name: 'db-seed',
    configureServer(server) {
      const send = (res, code, body) => {
        res.statusCode = code
        res.setHeader('Content-Type', 'application/json')
        res.end(JSON.stringify(body))
      }
      const route = (handler) => async (req, res, next) => {
        if (req.method !== 'POST') return next()
        try {
          send(res, 200, await handler(await readJsonBody(req)))
        } catch (err) {
          send(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      }

      server.middlewares.use('/api/db-seed-remove', route(handleRemove))
      server.middlewares.use('/api/db-seed-apply', route(handleApply))
      server.middlewares.use('/api/db-seed', async (req, res, next) => {
        try {
          if (req.method === 'GET') {
            const url = new URL(req.url, 'http://localhost')
            return send(res, 200, await handleGet(url.searchParams.get('system'), url.searchParams.get('id')))
          }
          if (req.method === 'POST') return send(res, 200, await handleAdd(await readJsonBody(req)))
          return next()
        } catch (err) {
          send(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })
    },
  }
}
