// Vite dev-server plugin: author gRPC contracts and attach them to services.
//
//   GET    /api/grpc-contracts?system=<id>
//     -> { ok, contracts: [{ name, methods, instruction, conversationId }] }
//   POST   /api/grpc-contracts  { system, contract, method, request?, response?,
//                                 responseStreaming?, instruction, conversationId }
//     -> upserts a method into a contract in the per-system registry. The proto,
//        pb2/pb2_grpc, and the shared servicer are generated by the Claude session
//        the modal then launches (sandbox-grpc-contract skill) — not here.
//   POST   /api/grpc-contracts  { system, protoFile, instruction, conversationId }
//     -> the *upload* path (body carries `protoFile`): validates a complete .proto
//        with the real protoc compiler, and only on success writes the .proto +
//        registers every rpc method. The pb2/pb2_grpc + shared servicer are still
//        generated by the launched session. Validation failures (e.g. an undefined
//        message) are returned verbatim so the user sees exactly what's wrong.
//   DELETE /api/grpc-contracts  { system, contract }
//     -> removes the registry entry + generated files and scrubs the contract from
//        every service's manifest `grpc` block.
//   GET    /api/grpc-service?system=<id>&id=<service>
//     -> { ok, grpc, contracts, services }  (a service's grpc block + the contracts
//        it can pick from + sibling service ids it can target)
//   POST   /api/grpc-attach  { system, service, contract, asServer, asClient,
//                              targets?, override?, conversationId }
//     -> writes the service's manifest `grpc` block immediately (so the diagram
//        draws gRPC edges at the next poll). The actual app.py / Dockerfile wiring
//        is done by the launched session (sandbox-grpc-attach skill).
//
// Mirrors endpoints.js (registry-JSON upsert, no docker rebuild — codegen is the
// session's job) + eventstreams.js (validation/plugin shape). A gRPC contract is a
// per-system registry, NOT a diagram node: roles (server/client) are per-contract
// and live on the service nodes, which is also what the frontend draws edges from.
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { systemDir, isValidSystem } from './systems.js'

const pexec = promisify(execFile)

class HttpError extends Error {
  constructor(status, message) {
    super(message)
    this.statusCode = status
  }
}
const bad = (msg) => new HttpError(400, msg)

// PascalCase for a proto service (contract) and its RPC methods.
const CONTRACT_RE = /^[A-Z][A-Za-z0-9]*$/
const METHOD_RE = /^[A-Z][A-Za-z0-9]*$/
// snake_case-ish proto field names.
const FIELD_RE = /^[a-z][a-z0-9_]*$/
// Scalar proto types we let the modal emit; `repeated <scalar>` is also allowed.
const SCALAR_TYPES = new Set([
  'double', 'float', 'int32', 'int64', 'uint32', 'uint64', 'sint32', 'sint64',
  'fixed32', 'fixed64', 'sfixed32', 'sfixed64', 'bool', 'string', 'bytes',
])

function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    let data = ''
    req.on('data', (chunk) => {
      data += chunk
      if (data.length > 200_000) reject(bad('request body too large'))
    })
    req.on('end', () => {
      if (!data) return resolve({})
      try {
        resolve(JSON.parse(data))
      } catch {
        reject(bad('invalid JSON body'))
      }
    })
    req.on('error', reject)
  })
}

const grpcDir = (system) => path.join(systemDir(system), 'grpc')
const registryFile = (system) => path.join(grpcDir(system), '_registry.json')
const manifestFile = (system) => path.join(systemDir(system), 'manifest.json')

function readManifest(system) {
  return JSON.parse(fs.readFileSync(manifestFile(system), 'utf8'))
}
function writeManifest(system, manifest) {
  fs.writeFileSync(manifestFile(system), JSON.stringify(manifest, null, 2) + '\n')
}

// Tolerates a missing/garbled registry — a system with no contracts yet.
function readRegistry(system) {
  try {
    const raw = JSON.parse(fs.readFileSync(registryFile(system), 'utf8'))
    return raw && typeof raw.contracts === 'object' && raw.contracts ? raw : { contracts: {} }
  } catch {
    return { contracts: {} }
  }
}
function writeRegistry(system, registry) {
  fs.mkdirSync(grpcDir(system), { recursive: true })
  fs.writeFileSync(registryFile(system), JSON.stringify(registry, null, 2) + '\n')
}

// A flat { field_name: type } map, where type is a scalar or `repeated <scalar>`.
// Empty/absent -> {} (the contract author lets Claude infer the shape).
function validateFields(value, label) {
  if (value == null) return {}
  if (typeof value !== 'object' || Array.isArray(value)) throw bad(`${label} must be a JSON object`)
  const out = {}
  for (const [k, v] of Object.entries(value)) {
    if (!FIELD_RE.test(k)) throw bad(`${label} field name "${k}" must be snake_case`)
    if (typeof v !== 'string') throw bad(`${label}.${k} must be a proto type name`)
    const base = v.startsWith('repeated ') ? v.slice('repeated '.length) : v
    if (!SCALAR_TYPES.has(base)) throw bad(`${label}.${k} has unknown proto type "${v}"`)
    out[k] = v
  }
  return out
}

// service nodes are the only things a contract can be attached to / target.
function serviceIds(manifest) {
  return manifest.nodes.filter((n) => n.type === 'service').map((n) => n.id)
}

// ---------------------------------------------------------------------------
// Contract authoring (registry only — the session generates the code)
// ---------------------------------------------------------------------------

function listContracts(system) {
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const { contracts } = readRegistry(system)
  const out = Object.entries(contracts).map(([name, c]) => ({
    name,
    methods: Array.isArray(c.methods) ? c.methods : [],
    instruction: typeof c.instruction === 'string' ? c.instruction : '',
    conversationId: c.conversationId || null,
  }))
  out.sort((a, b) => a.name.localeCompare(b.name))
  return { ok: true, contracts: out }
}

function upsertContractMethod(body) {
  const { system } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)

  const contract = body.contract
  if (typeof contract !== 'string' || !CONTRACT_RE.test(contract)) {
    throw bad('contract must be PascalCase (e.g. ChunkTransfer)')
  }
  const method = body.method
  if (typeof method !== 'string' || !METHOD_RE.test(method)) {
    throw bad('method must be PascalCase (e.g. GetChunk)')
  }
  const request = validateFields(body.request, 'request')
  const response = validateFields(body.response, 'response')
  const responseStreaming = !!body.responseStreaming
  const instruction = typeof body.instruction === 'string' ? body.instruction : ''
  if (instruction.length > 8000) throw bad('instruction is too long')
  const conversationId = body.conversationId
  if (typeof conversationId !== 'string') throw bad('conversationId is required')

  const registry = readRegistry(system)
  const existing = registry.contracts[contract] || {
    instruction: '',
    methods: [],
    conversationId,
    createdAt: new Date().toISOString(),
  }
  const methods = Array.isArray(existing.methods) ? existing.methods : []
  const record = { name: method, request, response, responseStreaming }
  const i = methods.findIndex((m) => m.name === method)
  if (i >= 0) methods[i] = record
  else methods.push(record)

  registry.contracts[contract] = {
    ...existing,
    methods,
    // The latest authoring instruction drives the (re)generated shared servicer.
    instruction: instruction || existing.instruction,
    conversationId,
  }
  writeRegistry(system, registry)
  return { ok: true, contract, method: record }
}

// ---------------------------------------------------------------------------
// Upload an existing .proto (validated by the real compiler before registering)
// ---------------------------------------------------------------------------

// Drop // line and /* */ block comments so a comment can't fake a `service`/
// `import` token (or hide one) during the structural checks below.
function stripProtoComments(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
}

// rpc <Name> ( [stream] <Req> ) returns ( [stream] <Res> )  — body or `;` either way.
const RPC_RE =
  /\brpc\s+([A-Za-z_]\w*)\s*\(\s*(stream\s+)?([A-Za-z_][\w.]*)\s*\)\s*returns\s*\(\s*(stream\s+)?([A-Za-z_][\w.]*)\s*\)/g

// Compile the uploaded proto with the real protoc (grpc_tools) inside a throwaway
// container that mounts ONLY a temp copy — the authoritative "is it complete?"
// check. The proto text only ever lands in the mounted file, never a shell arg;
// `contract` is PascalCase-validated, so it is safe to interpolate into the script.
async function runProtocValidate(contract, protoFile) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'grpc-validate-'))
  try {
    fs.writeFileSync(path.join(tmp, `${contract}.proto`), protoFile)
    // Quiet pip entirely (its warnings/notices go to stderr) so only protoc's own
    // diagnostics survive on failure.
    const script =
      `pip install -q --root-user-action=ignore grpcio-tools >/dev/null 2>&1 && ` +
      `python -m grpc_tools.protoc -I /g --python_out=/g --grpc_python_out=/g ${contract}.proto`
    await pexec(
      'docker',
      ['run', '--rm', '-v', `${tmp}:/g`, '-w', '/g', 'python:3.12-slim', 'sh', '-c', script],
      { timeout: 180_000, maxBuffer: 16 * 1024 * 1024 },
    )
  } catch (err) {
    // Strip the container mount prefix so messages read "<Contract>.proto:LINE:COL: …".
    const detail = `${err.stderr || ''}${err.stdout || ''}`.replaceAll('/g/', '').trim()
    // protoc diagnostics name the file: "<Contract>.proto:LINE:COL: ...". Anything
    // else (image pull, pip, daemon down) is an infra failure, not a bad proto.
    if (detail.includes(`${contract}.proto:`)) {
      throw new HttpError(400, `the .proto did not compile:\n${detail}`)
    }
    throw new HttpError(500, `proto validation could not run (is Docker available?):\n${detail || err.message}`)
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true })
  }
}

async function uploadContract(body) {
  const { system } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)

  const protoFile = body.protoFile
  if (typeof protoFile !== 'string' || !protoFile.trim()) throw bad('protoFile (the .proto text) is required')
  if (protoFile.length > 200_000) throw bad('proto file is too large')
  const conversationId = body.conversationId
  if (typeof conversationId !== 'string') throw bad('conversationId is required')
  const instruction = typeof body.instruction === 'string' ? body.instruction : ''
  if (instruction.length > 8000) throw bad('instruction is too long')

  // Structural completeness checks (cheap, before docker) on a comment-stripped copy.
  const src = stripProtoComments(protoFile)
  if (!/\bsyntax\s*=\s*["']proto3["']\s*;/.test(src)) {
    throw bad('the .proto must declare syntax = "proto3";')
  }
  if (/^\s*import\s+/m.test(src)) {
    throw bad('uploaded contracts must be self-contained — remove the import statement(s)')
  }
  const serviceNames = [...src.matchAll(/\bservice\s+([A-Za-z_]\w*)\s*\{/g)].map((m) => m[1])
  if (serviceNames.length === 0) throw bad('no service defined — a contract needs exactly one `service`')
  if (serviceNames.length > 1) {
    throw bad(`found ${serviceNames.length} services (${serviceNames.join(', ')}) — a contract is exactly one service per file`)
  }
  const contract = serviceNames[0]
  if (!CONTRACT_RE.test(contract)) throw bad(`service name "${contract}" must be PascalCase (e.g. ChunkTransfer)`)

  const methods = [...src.matchAll(RPC_RE)].map((m) => ({
    name: m[1],
    request: {},
    response: {},
    requestType: m[3],
    responseType: m[5],
    requestStreaming: !!m[2],
    responseStreaming: !!m[4],
  }))
  if (methods.length === 0) throw bad(`service ${contract} has no rpc methods`)

  // The real protoc gate — catches undefined/dangling types, duplicate or missing
  // field numbers, and syntax errors. Nothing is written if this throws.
  if (process.env.GRPC_SKIP_PROTOC !== '1') await runProtocValidate(contract, protoFile)

  // Persist: the proto verbatim (file stem = service = registry key) + the registry
  // entry (replacing any prior contract of this name — the upload is authoritative).
  fs.mkdirSync(grpcDir(system), { recursive: true })
  fs.writeFileSync(path.join(grpcDir(system), `${contract}.proto`), protoFile)
  const registry = readRegistry(system)
  registry.contracts[contract] = {
    instruction,
    methods,
    conversationId,
    createdAt: registry.contracts[contract]?.createdAt || new Date().toISOString(),
    source: 'upload',
  }
  writeRegistry(system, registry)
  return { ok: true, contract, methods }
}

function deleteContract(body) {
  const { system } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const contract = body.contract
  if (typeof contract !== 'string' || !CONTRACT_RE.test(contract)) throw bad('invalid contract')

  // 1. registry
  const registry = readRegistry(system)
  delete registry.contracts[contract]
  writeRegistry(system, registry)

  // 2. generated files (shared)
  for (const suffix of ['.proto', '_pb2.py', '_pb2_grpc.py', '_servicer.py']) {
    fs.rmSync(path.join(grpcDir(system), `${contract}${suffix}`), { force: true })
  }

  // 3. scrub every service's grpc block + any per-service override file
  const manifest = readManifest(system)
  for (const node of manifest.nodes) {
    if (!node.grpc) continue
    const g = node.grpc
    g.servers = (g.servers || []).filter((c) => c !== contract)
    g.clients = (g.clients || []).filter((c) => c.contract !== contract)
    g.overrides = (g.overrides || []).filter((c) => c !== contract)
    if (!g.servers.length && !g.clients.length && !g.overrides.length) delete node.grpc
    fs.rmSync(path.join(systemDir(system), node.id, 'grpc', `${contract}_servicer_override.py`), { force: true })
  }
  writeManifest(system, manifest)
  return { ok: true, removed: contract }
}

// ---------------------------------------------------------------------------
// Attach: write a service node's manifest `grpc` block (edges + wiring source)
// ---------------------------------------------------------------------------

function getService(system, id) {
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const manifest = readManifest(system)
  const node = manifest.nodes.find((n) => n.id === id)
  if (!node || node.type !== 'service') throw bad(`"${id}" is not a service in this system`)
  return {
    ok: true,
    grpc: node.grpc || { servers: [], clients: [], overrides: [] },
    contracts: listContracts(system).contracts.map((c) => c.name),
    services: serviceIds(manifest).filter((s) => s !== id),
  }
}

function attachContract(body) {
  const { system } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
  const manifest = readManifest(system)

  const service = body.service
  const node = manifest.nodes.find((n) => n.id === service)
  if (!node || node.type !== 'service') throw bad(`"${service}" is not a service in this system`)

  const contract = body.contract
  if (typeof contract !== 'string' || !CONTRACT_RE.test(contract)) throw bad('invalid contract')
  if (!readRegistry(system).contracts[contract]) throw bad(`contract "${contract}" does not exist`)

  const asServer = !!body.asServer
  const asClient = !!body.asClient
  const override = !!body.override

  // Targets only matter for a client; must be real service nodes in this system.
  const allServices = new Set(serviceIds(manifest))
  let targets = []
  if (asClient) {
    targets = (Array.isArray(body.targets) ? body.targets : []).filter((t) => typeof t === 'string')
    for (const t of targets) {
      if (!allServices.has(t)) throw bad(`target "${t}" is not a service in this system`)
    }
    targets = [...new Set(targets)]
  }

  const g = node.grpc || { servers: [], clients: [], overrides: [] }
  g.servers = g.servers || []
  g.clients = g.clients || []
  g.overrides = g.overrides || []

  // Server role.
  g.servers = g.servers.filter((c) => c !== contract)
  if (asServer) g.servers.push(contract)

  // Client role (+ its editable targets).
  g.clients = g.clients.filter((c) => c.contract !== contract)
  if (asClient) g.clients.push({ contract, targets })

  // Override flag (only meaningful when serving).
  g.overrides = g.overrides.filter((c) => c !== contract)
  if (override && asServer) g.overrides.push(contract)

  if (!g.servers.length && !g.clients.length && !g.overrides.length) delete node.grpc
  else node.grpc = g

  writeManifest(system, manifest)
  return { ok: true, service, grpc: node.grpc || { servers: [], clients: [], overrides: [] } }
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

export default function grpc() {
  return {
    name: 'grpc-contracts',
    configureServer(server) {
      const json = (res, code, body) => {
        res.statusCode = code
        res.setHeader('Content-Type', 'application/json')
        res.end(JSON.stringify(body))
      }

      server.middlewares.use('/api/grpc-contracts', async (req, res, next) => {
        try {
          if (req.method === 'GET') {
            const system = new URL(req.url, 'http://localhost').searchParams.get('system')
            return json(res, 200, listContracts(system))
          }
          if (req.method === 'POST') {
            const body = await readJsonBody(req)
            // The upload path carries the whole .proto; the form path upserts one method.
            if (body && typeof body.protoFile === 'string') {
              return json(res, 200, await uploadContract(body))
            }
            return json(res, 200, upsertContractMethod(body))
          }
          if (req.method === 'DELETE') {
            return json(res, 200, deleteContract(await readJsonBody(req)))
          }
          return next()
        } catch (err) {
          return json(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })

      server.middlewares.use('/api/grpc-service', async (req, res, next) => {
        if (req.method !== 'GET') return next()
        try {
          const url = new URL(req.url, 'http://localhost')
          return json(res, 200, getService(url.searchParams.get('system'), url.searchParams.get('id')))
        } catch (err) {
          return json(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })

      server.middlewares.use('/api/grpc-attach', async (req, res, next) => {
        if (req.method !== 'POST') return next()
        try {
          return json(res, 200, attachContract(await readJsonBody(req)))
        } catch (err) {
          return json(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })
    },
  }
}
