// Vite dev-server plugin: put a per-service load balancer in front of a service.
//
//   GET  /api/service-lb?system=<id>
//     -> { ok, groups: [{ service, algorithm, instances: ["<name>-1", ...] }] }
//   POST /api/service-lb  { system, service, instances, algorithm }
//     -> the idempotent "set desired state" op: enable (1 -> N), scale up/down,
//        change the balancing algorithm, or disable (N -> 1). Mechanical — no
//        launched Claude session (like Add read replica / Add WebSockets).
//
// The model (see .claude/skills/sandbox-service-lb): a load-balanced service keeps
// its node id `<name>` as the CLUSTER ENTRY. On enable, the `<name>` compose service
// is swapped from the FastAPI build to an haproxy sidecar (HTTP mode) that binds the
// same :8000 and balances across N real instances `<name>-1..N` (each `build: ./<name>`
// — the same image). Because `<name>` keeps the network name, EVERY existing caller
// balances with zero edits: the main nginx `upstream <name> { server <name>:8000; }`
// and any `http://<name>:8000` service-to-service call both resolve to the sidecar.
// nginx.conf is never touched. The `<name>` node keeps owning endpoints.json/grpc, so
// `/<name>/…` stays routable and discoverable; only its `type` flips to `service-lb`
// and its metrics become haproxy's. Instances carry `instanceOf: "<name>"` (the
// grouping key the diagram stacks on, like wsTier/replicaOf).
//
// Mirrors websockets.js / replicas.js: comment-preserving YAML edits, strict
// whitelist validation (user input only ever lands in generated files), and a
// frontend-safe `docker compose` rebuild — never ./start.sh.
import fs from 'node:fs'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { repoRoot, systemsDir, systemDir, isValidSystem } from './systems.js'
import {
  HttpError, bad, NAME_RE, readJsonBody, serviceMetrics, serviceHealth,
  composePath, loadCompose, saveCompose, composeServiceDef, setComposeService,
  removeComposeService, loadPrometheus, savePrometheus, addScrapeJobDoc,
  removeScrapeJobDoc, setScrapeJobTarget,
} from './scaffold.js'

const pexec = promisify(execFile)

// haproxy binds the service's own :8000 so it transparently fronts `<name>`; its
// native prometheus exporter is on a separate HTTP frontend (:8405, scraped over the
// docker net). Instances serve FastAPI on :8000, one container each.
const LB_PORT = 8000
const STATS_PORT = 8405
const SERVICE_PORT = 8000

const ALGORITHMS = ['roundrobin', 'leastconn', 'source']
const MIN_INSTANCES = 1
const MAX_INSTANCES = 8

const HAPROXY_IMAGE = 'haproxy:3.0-alpine'

const HEALTH_RULES = [
  { color: 'red', when: 'value < 1' },
  { color: 'green', when: 'value >= 1' },
]

// ---------------------------------------------------------------------------
// File IO helpers
// ---------------------------------------------------------------------------

function readManifest(system) {
  return JSON.parse(fs.readFileSync(path.join(systemDir(system), 'manifest.json'), 'utf8'))
}
function writeManifest(system, manifest) {
  fs.writeFileSync(
    path.join(systemDir(system), 'manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n',
  )
}
const lbCfgDir = (system, service) => path.join(systemDir(system), `${service}-lb`)

// ---------------------------------------------------------------------------
// haproxy.cfg — rendered from the manifest svcLb block (never hand-edited server
// lines). HTTP mode, `option httpchk GET /health` so a failing instance is ejected
// (the per-instance failure handling behind the uniform cluster breaker), one
// `server` line per instance, plus the native prometheus exporter frontend. The
// `resolvers docker` / `init-addr libc,none` block re-resolves instance hostnames at
// runtime so a recreated instance (new IP) recovers without an lb restart — exactly
// like the websocket tier's haproxy.
// ---------------------------------------------------------------------------

function renderHaproxyCfg(service, algorithm, instances) {
  const serverLines = instances
    .map((s) => `    server ${s} ${s}:${SERVICE_PORT} check resolvers docker init-addr libc,none`)
    .join('\n')
  return `# HTTP load balancer for service "${service}" — generated by Load Balancing.
# Regenerated from manifest svcLb when the group changes; do not hand-edit the server lines.
global
    log stdout format raw local0

resolvers docker
    nameserver dns1 127.0.0.11:53
    resolve_retries 3
    timeout resolve 1s
    timeout retry   1s
    hold valid      10s
    hold obsolete   10s

defaults
    mode http
    log global
    option httplog
    timeout connect 5s
    timeout client  30s
    timeout server  30s

frontend http_in
    bind *:${LB_PORT}
    default_backend svc_backends

backend svc_backends
    balance ${algorithm}
    option httpchk GET /health
${serverLines}

# haproxy's built-in prometheus exporter, on its own HTTP frontend.
frontend stats
    bind *:${STATS_PORT}
    http-request use-service prometheus-exporter if { path /metrics }
`
}

function writeHaproxyCfg(system, service, algorithm, instances) {
  const dir = lbCfgDir(system, service)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, 'haproxy.cfg'), renderHaproxyCfg(service, algorithm, instances))
}

// ---------------------------------------------------------------------------
// Manifest node metrics
// ---------------------------------------------------------------------------

// The cluster-entry (haproxy) metrics: live sessions, request rate, instances up.
function lbMetrics(service) {
  return [
    { label: 'sessions', query: `sum(haproxy_backend_current_sessions{job="${service}",proxy="svc_backends"}) or vector(0)`, unit: '' },
    { label: 'req/s', query: `sum(rate(haproxy_frontend_http_requests_total{job="${service}",proxy="http_in"}[1m])) or vector(0)`, unit: '/s' },
    { label: 'up', query: `count(haproxy_server_status{job="${service}",proxy="svc_backends",state="UP"} == 1) or vector(0)`, unit: '' },
  ]
}
function lbHealth(service) {
  return { query: `up{job="${service}"}`, rules: HEALTH_RULES }
}

// ---------------------------------------------------------------------------
// compose / prometheus splices
//
// The generic document helpers (loadCompose / setComposeService / addScrapeJobDoc / …)
// now live in scaffold.js and are shared with the worker replica-group flow. Only the
// two service-lb-specific pieces stay here.
// ---------------------------------------------------------------------------

// The plain-JS form of the `<name>` compose service (the app), captured so instances
// can clone its build/env/volumes (preserving anything wired onto it — e.g. a
// resilience wrapper's SERVICE_ID + manifest mount — so outbound behavior survives
// the split, uniformly across every instance). Falls back to a clean build.
function appServiceDef(doc, service) {
  return composeServiceDef(doc, service) || { build: `./${service}` }
}

// haproxy sidecar def taking over the `<name>` compose service (same :8000 → it keeps
// the network name and transparently fronts the cluster).
function sidecarDef(service, instances) {
  return {
    image: HAPROXY_IMAGE,
    volumes: [`./${service}-lb/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro`],
    depends_on: [...instances],
    // depends_on only waits for the instance CONTAINERS to start, not for them to
    // accept requests; haproxy's `init-addr` lets it boot regardless and its
    // resolvers re-check, so keep it up.
    restart: 'unless-stopped',
  }
}

// ---------------------------------------------------------------------------
// Rebuild (frontend-safe — NEVER ./start.sh)
// ---------------------------------------------------------------------------

async function dockerRebuild(system, { buildNames = [], recreate = [], removeOrphans = false }) {
  if (process.env.SERVICE_LB_SKIP_REBUILD === '1') return '(rebuild skipped)'
  const compose = composePath(system)
  // 600s: the first instance build pulls python:3.12-slim + pip installs.
  const opts = { cwd: repoRoot, timeout: 600_000, maxBuffer: 16 * 1024 * 1024 }
  const run = async (args) => {
    const r = await pexec('docker', ['compose', '-f', compose, ...args], opts)
    return r.stdout + r.stderr
  }
  let log = ''
  try {
    // Build ONLY the named instance images (a bare `up -d --build` rebuilds every
    // build: service in the system).
    if (buildNames.length) log += await run(['build', ...buildNames])
    const upArgs = ['up', '-d']
    if (removeOrphans) upArgs.push('--remove-orphans')
    log += await run(upArgs)
    // Force-recreate the sidecar so it re-reads a regenerated haproxy.cfg, and the lb
    // so nginx re-resolves `<name>` (now the sidecar). `nginx -t` validates the fresh
    // lb container (macOS single-file bind-mount stale-inode workaround, like scaffold.js).
    for (const svc of recreate) log += await run(['up', '-d', '--force-recreate', svc])
    log += await run(['exec', '-T', 'lb', 'nginx', '-t'])
    log += await run(['restart', 'prometheus'])
  } catch (err) {
    const detail = `${err.stdout || ''}${err.stderr || ''}` || err.message
    throw new HttpError(500, `docker compose failed:\n${detail}`)
  }
  return log
}

// ---------------------------------------------------------------------------
// Reading current state
// ---------------------------------------------------------------------------

// A node that can host a per-service load balancer: a plain generated service that is
// not itself an instance and not already infra (lb/prometheus are not create-service).
function isBalanceableService(node) {
  return (
    node &&
    node.type === 'service' &&
    node.origin === 'create-service' &&
    !node.instanceOf
  )
}

function instanceNodes(manifest, service) {
  return manifest.nodes
    .filter((n) => n.instanceOf === service)
    .sort((a, b) => instanceOrdinal(a.id, service) - instanceOrdinal(b.id, service))
}
function instanceOrdinal(id, service) {
  const m = new RegExp(`^${service}-(\\d+)$`).exec(id)
  return m ? Number(m[1]) : 0
}
function instanceId(service, ordinal) {
  return `${service}-${ordinal}`
}

// The public shape for GET.
function listGroups(system) {
  const manifest = readManifest(system)
  const groups = manifest.nodes
    .filter((n) => n.type === 'service-lb' && n.svcLb)
    .map((n) => ({
      service: n.id,
      algorithm: n.svcLb.algorithm,
      instances: instanceNodes(manifest, n.id).map((i) => i.id),
    }))
  return { ok: true, groups }
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validate(body) {
  const { system } = body
  if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)

  const service = typeof body.service === 'string' ? body.service : ''
  // instance ids `<service>-N` must stay inside NAME_RE's practical cap.
  if (!NAME_RE.test(service) || service.length > 30) {
    throw bad('service must be lowercase letters, digits and hyphens (start with a letter, max 30 chars)')
  }

  const instances = Number(body.instances)
  if (!Number.isInteger(instances) || instances < MIN_INSTANCES || instances > MAX_INSTANCES) {
    throw bad(`instances must be a whole number between ${MIN_INSTANCES} and ${MAX_INSTANCES}`)
  }

  const algorithm = body.algorithm === undefined ? 'roundrobin' : body.algorithm
  if (!ALGORITHMS.includes(algorithm)) {
    throw bad(`algorithm must be one of: ${ALGORITHMS.join(', ')}`)
  }

  const manifest = readManifest(system)
  const node = manifest.nodes.find((n) => n.id === service)
  if (!node) throw bad(`no node "${service}" in this system`)
  const loadBalanced = node.type === 'service-lb' && !!node.svcLb
  if (!loadBalanced && !isBalanceableService(node)) {
    throw bad(`"${service}" is not a load-balanceable service`)
  }
  return { system, service, instances, algorithm, manifest, node, loadBalanced }
}

// Reject a derived instance id that collides with something we don't own.
function assertFreeInstanceIds(system, manifest, service, ordinals) {
  const composeSrc = fs.readFileSync(composePath(system), 'utf8')
  for (const ord of ordinals) {
    const id = instanceId(service, ord)
    if (manifest.nodes.some((n) => n.id === id && n.instanceOf !== service)) {
      throw bad(`a node named "${id}" already exists in this system`)
    }
    if (fs.existsSync(path.join(systemDir(system), id))) {
      throw bad(`systems/${system}/${id}/ already exists`)
    }
    if (new RegExp(`^  ${id}:`, 'm').test(composeSrc) && !manifest.nodes.some((n) => n.id === id)) {
      throw bad(`a compose service named "${id}" already exists in this system`)
    }
  }
}

// ---------------------------------------------------------------------------
// The transitions
// ---------------------------------------------------------------------------

// ENABLE: plain service `<name>` -> cluster of N instances behind an haproxy sidecar
// that keeps the `<name>` name. No registry migration: `<name>` keeps owning
// endpoints.json / grpc; only its compose service, scrape target, node type + metrics
// change, and the instances are added.
function enable(ctx) {
  const { system, service, instances, algorithm, manifest, node } = ctx
  const ordinals = Array.from({ length: instances }, (_, i) => i + 1)
  assertFreeInstanceIds(system, manifest, service, ordinals)
  const ids = ordinals.map((o) => instanceId(service, o))

  // 1. compose: capture the app def, add instances cloning it, swap `<name>` -> sidecar
  const doc = loadCompose(system)
  const app = appServiceDef(doc, service)
  for (const id of ids) {
    setComposeService(doc, id, { ...app, build: `./${service}` }, ` Instance of load-balanced service "${service}"`)
  }
  setComposeService(doc, service, sidecarDef(service, ids), ` Load balancer sidecar for "${service}" (haproxy)`)
  saveCompose(system, doc)

  // 2. prometheus: repoint `<name>` to the haproxy exporter, add a job per instance
  const prom = loadPrometheus(system)
  setScrapeJobTarget(prom, service, `${service}:${STATS_PORT}`)
  for (const id of ids) {
    addScrapeJobDoc(prom, id, `${id}:${SERVICE_PORT}`, ` Instance of load-balanced service "${service}"`)
  }
  savePrometheus(system, prom)

  // 3. haproxy.cfg
  writeHaproxyCfg(system, service, algorithm, ids)

  // 4. manifest: flip `<name>` to the cluster entry, add instance nodes + edges
  node.type = 'service-lb'
  node.loadBalanced = true
  node.svcLb = { algorithm, instances: [...ids] }
  node.metrics = lbMetrics(service)
  node.health = lbHealth(service)
  for (const id of ids) {
    manifest.nodes.push(instanceNode(service, id, node))
  }
  manifest.edges = [...(manifest.edges || []), ...ids.map((id) => ({ from: service, to: id, origin: 'service-lb' }))]
  writeManifest(system, manifest)

  return { buildNames: ids, recreate: [service, 'lb'], removeOrphans: false }
}

// A fresh instance node: a normal service card that carries the grouping back-link and
// no endpoints of its own (endpoints stay owned by the `<name>` entry).
function instanceNode(service, id, entryNode) {
  return {
    id,
    label: id,
    type: 'service',
    origin: 'create-service',
    instanceOf: service,
    position: { x: (entryNode.position?.x ?? 80) + 260, y: (entryNode.position?.y ?? 80) },
    metrics: serviceMetrics(id),
    health: serviceHealth(id),
  }
}

// SCALE / ALGORITHM: `<name>` stays a cluster entry; add or drop the highest-ordinal
// instances to reach the target count, and/or change the balance algorithm.
function scale(ctx) {
  const { system, service, instances, algorithm, manifest, node } = ctx
  const current = instanceNodes(manifest, service)
  const currentIds = current.map((n) => n.id)
  const target = instances

  const doc = loadCompose(system)
  const prom = loadPrometheus(system)
  const buildNames = []
  let removed = false

  if (target > current.length) {
    // scale up: clone one existing instance's compose def for the new ones
    const app = current.length ? appServiceDef(doc, currentIds[0]) : appServiceDef(doc, service)
    const maxOrd = current.reduce((m, n) => Math.max(m, instanceOrdinal(n.id, service)), 0)
    for (let o = maxOrd + 1; buildNames.length < target - current.length; o++) {
      const id = instanceId(service, o)
      assertFreeInstanceIds(system, manifest, service, [o])
      setComposeService(doc, id, { ...app, build: `./${service}` }, ` Instance of load-balanced service "${service}"`)
      addScrapeJobDoc(prom, id, `${id}:${SERVICE_PORT}`, ` Instance of load-balanced service "${service}"`)
      manifest.nodes.push(instanceNode(service, id, node))
      manifest.edges.push({ from: service, to: id, origin: 'service-lb' })
      buildNames.push(id)
    }
  } else if (target < current.length) {
    // scale down: drop the highest ordinals
    const drop = current.slice(target)
    for (const n of drop) {
      removeComposeService(doc, n.id)
      removeScrapeJobDoc(prom, n.id)
    }
    const dropIds = new Set(drop.map((n) => n.id))
    manifest.nodes = manifest.nodes.filter((n) => !dropIds.has(n.id))
    manifest.edges = (manifest.edges || []).filter((e) => !dropIds.has(e.from) && !dropIds.has(e.to))
    removed = true
  }

  const finalIds = instanceNodes(manifest, service).map((n) => n.id)
  // keep the sidecar's depends_on in step with the instance set
  setComposeService(doc, service, sidecarDef(service, finalIds), ` Load balancer sidecar for "${service}" (haproxy)`)
  saveCompose(system, doc)
  savePrometheus(system, prom)
  writeHaproxyCfg(system, service, algorithm, finalIds)
  node.svcLb = { algorithm, instances: [...finalIds] }
  writeManifest(system, manifest)

  return { buildNames, recreate: [service, 'lb'], removeOrphans: removed }
}

// DISABLE: collapse the cluster back to a single plain service `<name>`. The app runs
// directly in `<name>` again (rebuilt from ./<name>, restoring the build/env/volumes
// captured from an instance); every instance + the haproxy sidecar role + cfg folder
// are removed. endpoints.json / grpc were never moved, so nothing to restore there.
function disable(ctx) {
  const { system, service, manifest, node } = ctx
  const current = instanceNodes(manifest, service)
  const doc = loadCompose(system)
  const prom = loadPrometheus(system)

  // restore the plain app compose service from an instance's def (falls back to a
  // clean build if there are somehow no instances)
  const app = current.length ? appServiceDef(doc, current[0].id) : { build: `./${service}` }
  const restored = { ...app, build: `./${service}` }
  delete restored.depends_on // the sidecar's dep on instances; the app has none of its own here
  for (const n of current) {
    removeComposeService(doc, n.id)
    removeScrapeJobDoc(prom, n.id)
  }
  setComposeService(doc, service, restored, ` Service "${service}"`)
  setScrapeJobTarget(prom, service, `${service}:${SERVICE_PORT}`)
  saveCompose(system, doc)
  savePrometheus(system, prom)

  // manifest: back to a plain service node
  const dropIds = new Set(current.map((n) => n.id))
  manifest.nodes = manifest.nodes.filter((n) => !dropIds.has(n.id))
  manifest.edges = (manifest.edges || []).filter((e) => !dropIds.has(e.from) && !dropIds.has(e.to))
  node.type = 'service'
  delete node.loadBalanced
  delete node.svcLb
  node.metrics = serviceMetrics(service)
  node.health = serviceHealth(service)
  writeManifest(system, manifest)

  // cfg folder is gone
  fs.rmSync(lbCfgDir(system, service), { recursive: true, force: true })

  return { buildNames: [service], recreate: ['lb'], removeOrphans: true }
}

export async function setLoadBalancing(body) {
  const ctx = validate(body)
  const { instances, loadBalanced, algorithm, node } = ctx

  let plan
  if (!loadBalanced) {
    if (instances <= 1) return { ok: true, node, log: '(already a single service — no load balancer)' }
    plan = enable(ctx)
  } else if (instances <= 1) {
    plan = disable(ctx)
  } else {
    const current = instanceNodes(ctx.manifest, ctx.service).length
    if (current === instances && node.svcLb.algorithm === algorithm) {
      return { ok: true, node, log: '(no change)' }
    }
    plan = scale(ctx)
  }

  const log = await dockerRebuild(ctx.system, plan)
  return { ok: true, node: readManifest(ctx.system).nodes.find((n) => n.id === ctx.service), log }
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

export default function serviceLb() {
  const json = (res, code, b) => {
    res.statusCode = code
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(b))
  }
  return {
    name: 'service-lb',
    configureServer(server) {
      server.middlewares.use('/api/service-lb', async (req, res, next) => {
        try {
          const url = new URL(req.url, 'http://localhost')
          if (url.pathname === '/' || url.pathname === '') {
            if (req.method === 'GET') {
              const system = url.searchParams.get('system')
              if (!isValidSystem(system)) throw bad(`unknown system "${system}"`)
              return json(res, 200, listGroups(system))
            }
            if (req.method === 'POST') {
              return json(res, 200, await setLoadBalancing(await readJsonBody(req)))
            }
          }
          return next()
        } catch (err) {
          return json(res, err.statusCode || 500, { ok: false, error: err.message })
        }
      })
    },
  }
}
