# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChunkTransfer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ChunkTransfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43hunkTransfer.proto\x12\x13\x64ownloadcoordinator\"6\n\x0c\x43hunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x05\x12\x14\n\x0crequester_id\x18\x02 \x01(\t\"Y\n\nChunkFrame\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32 .downloadcoordinator.ChunkHeaderH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x07\n\x05\x66rame\"?\n\x0b\x43hunkHeader\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t2a\n\rChunkTransfer\x12P\n\x08GetChunk\x12!.downloadcoordinator.ChunkRequest\x1a\x1f.downloadcoordinator.ChunkFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChunkTransfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKREQUEST']._serialized_start=44
  _globals['_CHUNKREQUEST']._serialized_end=98
  _globals['_CHUNKFRAME']._serialized_start=100
  _globals['_CHUNKFRAME']._serialized_end=189
  _globals['_CHUNKHEADER']._serialized_start=191
  _globals['_CHUNKHEADER']._serialized_end=254
  _globals['_CHUNKTRANSFER']._serialized_start=256
  _globals['_CHUNKTRANSFER']._serialized_end=353
# @@protoc_insertion_point(module_scope)
