# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Coordination.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'Coordination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43oordination.proto\x12\x13\x64ownloadcoordinator\"$\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x85\x01\n\x0c\x46ileManifest\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x13\n\x0b\x63hunk_count\x18\x02 \x01(\x05\x12\x12\n\nchunk_size\x18\x03 \x01(\x03\x12\x11\n\tfile_size\x18\x04 \x01(\x03\x12\x11\n\tfull_hash\x18\x05 \x01(\t\x12\x17\n\x0f\x63hunk_checksums\x18\x06 \x03(\t\"6\n\x11\x41ssignmentRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06\x62itmap\x18\x02 \x01(\x0c\"\x8f\x01\n\nAssignment\x12\x32\n\x04kind\x18\x01 \x01(\x0e\x32$.downloadcoordinator.Assignment.Kind\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x05\x12\x13\n\x0bsource_addr\x18\x03 \x01(\t\"&\n\x04Kind\x12\n\n\x06\x41SSIGN\x10\x00\x12\x08\n\x04WAIT\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\"E\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06\x62itmap\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t\":\n\x0f\x43ompleteRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66ull_hash_ok\x18\x02 \x01(\x08\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xe1\x02\n\x0c\x43oordination\x12S\n\x08Register\x12$.downloadcoordinator.RegisterRequest\x1a!.downloadcoordinator.FileManifest\x12\\\n\x11RequestAssignment\x12&.downloadcoordinator.AssignmentRequest\x1a\x1f.downloadcoordinator.Assignment\x12L\n\tHeartbeat\x12%.downloadcoordinator.HeartbeatRequest\x1a\x18.downloadcoordinator.Ack\x12P\n\x0eReportComplete\x12$.downloadcoordinator.CompleteRequest\x1a\x18.downloadcoordinator.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Coordination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=43
  _globals['_REGISTERREQUEST']._serialized_end=79
  _globals['_FILEMANIFEST']._serialized_start=82
  _globals['_FILEMANIFEST']._serialized_end=215
  _globals['_ASSIGNMENTREQUEST']._serialized_start=217
  _globals['_ASSIGNMENTREQUEST']._serialized_end=271
  _globals['_ASSIGNMENT']._serialized_start=274
  _globals['_ASSIGNMENT']._serialized_end=417
  _globals['_ASSIGNMENT_KIND']._serialized_start=379
  _globals['_ASSIGNMENT_KIND']._serialized_end=417
  _globals['_HEARTBEATREQUEST']._serialized_start=419
  _globals['_HEARTBEATREQUEST']._serialized_end=488
  _globals['_COMPLETEREQUEST']._serialized_start=490
  _globals['_COMPLETEREQUEST']._serialized_end=548
  _globals['_ACK']._serialized_start=550
  _globals['_ACK']._serialized_end=567
  _globals['_COORDINATION']._serialized_start=570
  _globals['_COORDINATION']._serialized_end=923
# @@protoc_insertion_point(module_scope)
