# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Coordination_pb2 as Coordination__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Coordination_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinationStub(object):
    """Coordination is served ONLY by the coordinator; every worker is a client. The
    coordinator hands out chunk assignments (load-balanced across all current holders),
    tracks liveness via heartbeats, and records completion.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/downloadcoordinator.Coordination/Register',
                request_serializer=Coordination__pb2.RegisterRequest.SerializeToString,
                response_deserializer=Coordination__pb2.FileManifest.FromString,
                _registered_method=True)
        self.RequestAssignment = channel.unary_unary(
                '/downloadcoordinator.Coordination/RequestAssignment',
                request_serializer=Coordination__pb2.AssignmentRequest.SerializeToString,
                response_deserializer=Coordination__pb2.Assignment.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/downloadcoordinator.Coordination/Heartbeat',
                request_serializer=Coordination__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=Coordination__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportComplete = channel.unary_unary(
                '/downloadcoordinator.Coordination/ReportComplete',
                request_serializer=Coordination__pb2.CompleteRequest.SerializeToString,
                response_deserializer=Coordination__pb2.Ack.FromString,
                _registered_method=True)


class CoordinationServicer(object):
    """Coordination is served ONLY by the coordinator; every worker is a client. The
    coordinator hands out chunk assignments (load-balanced across all current holders),
    tracks liveness via heartbeats, and records completion.
    """

    def Register(self, request, context):
        """A worker announces itself and learns the file manifest (chunking + checksums).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAssignment(self, request, context):
        """A worker pulls its next piece of work, carrying its current bitmap so the
        coordinator knows what it still needs. Completion of a chunk is signalled
        implicitly by the updated bitmap on the NEXT call — there is no chunk-complete RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic liveness + bitmap sync, on a separate cadence from work pulls.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportComplete(self, request, context):
        """Sent once, after a worker holds every chunk AND the full-file hash verifies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=Coordination__pb2.RegisterRequest.FromString,
                    response_serializer=Coordination__pb2.FileManifest.SerializeToString,
            ),
            'RequestAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAssignment,
                    request_deserializer=Coordination__pb2.AssignmentRequest.FromString,
                    response_serializer=Coordination__pb2.Assignment.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=Coordination__pb2.HeartbeatRequest.FromString,
                    response_serializer=Coordination__pb2.Ack.SerializeToString,
            ),
            'ReportComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportComplete,
                    request_deserializer=Coordination__pb2.CompleteRequest.FromString,
                    response_serializer=Coordination__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'downloadcoordinator.Coordination', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('downloadcoordinator.Coordination', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordination(object):
    """Coordination is served ONLY by the coordinator; every worker is a client. The
    coordinator hands out chunk assignments (load-balanced across all current holders),
    tracks liveness via heartbeats, and records completion.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloadcoordinator.Coordination/Register',
            Coordination__pb2.RegisterRequest.SerializeToString,
            Coordination__pb2.FileManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloadcoordinator.Coordination/RequestAssignment',
            Coordination__pb2.AssignmentRequest.SerializeToString,
            Coordination__pb2.Assignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloadcoordinator.Coordination/Heartbeat',
            Coordination__pb2.HeartbeatRequest.SerializeToString,
            Coordination__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/downloadcoordinator.Coordination/ReportComplete',
            Coordination__pb2.CompleteRequest.SerializeToString,
            Coordination__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
