-- Generated by "Add database". Runs once on first init of ledger-db.

-- Account: a balance bucket owned by some party, in a given currency.
CREATE TABLE IF NOT EXISTS account (
    id          bigint      PRIMARY KEY,                         -- snowflake id, set by app on insert
    name        text,                                            -- 'cash' | 'escrow' | 'income' | NULL (platform-relevant)
    type        text        NOT NULL,                            -- 'income' | 'asset' | 'liability'
    owner_id    text        NOT NULL,                            -- seller_id, 'platform', a psp (e.g. 'stripe'), or a payout service (e.g. 'tipalti')
    currency    varchar(3)  NOT NULL,
    CONSTRAINT account_name_check CHECK (name IN ('cash', 'escrow', 'income')),
    CONSTRAINT account_type_check CHECK (type IN ('income', 'asset', 'liability')),
    CONSTRAINT account_owner_name_unique UNIQUE (owner_id, name)
);

-- Transaction: one step of a payment order's lifecycle.
CREATE TABLE IF NOT EXISTS transaction (
    id                  bigint      PRIMARY KEY,                 -- snowflake id, set by app on insert
    payment_order_id    text        NOT NULL,                    -- snowflake id (string-typed)
    step                text        NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT transaction_step_check CHECK (step IN ('step1_payin', 'step2a_payin-complete', 'step2b_fufilled', 'refund', 'step3_payout', 'step4_payout-received')),
    CONSTRAINT transaction_payment_order_step_unique UNIQUE (payment_order_id, step)
);

-- Idempotent migration for pre-existing volumes: idempotency_key is no longer part of the
-- Transaction model (its "unique" directive was removed), so drop the column outright.
ALTER TABLE transaction DROP COLUMN IF EXISTS idempotency_key;

CREATE INDEX IF NOT EXISTS transaction_payment_order_id_idx ON transaction (payment_order_id);

-- LedgerEntry: a single debit/credit line posted against an account for a transaction.
CREATE TABLE IF NOT EXISTS ledger_entry (
    id              bigint      PRIMARY KEY,                     -- snowflake id, set by app on insert
    transaction_id  bigint      NOT NULL REFERENCES transaction (id),
    account_id      bigint      NOT NULL REFERENCES account (id),
    direction       text        NOT NULL,
    amount          integer     NOT NULL,
    currency        varchar(3)  NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ledger_entry_direction_check CHECK (direction IN ('debit', 'credit'))
);

-- Refund: a refund issued against a payment order.
-- Model shape is {id, payment_order_id, created_at}; transaction_id/amount/currency are
-- legacy columns from an earlier shape, kept (nullable) so existing rows aren't lost.
CREATE TABLE IF NOT EXISTS refund (
    id                  bigint      PRIMARY KEY,                 -- snowflake id, set by app on insert
    payment_order_id    text        NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    transaction_id      bigint      REFERENCES transaction (id), -- legacy; nullable (no longer in Refund model)
    amount              integer,                                 -- legacy; nullable (no longer in Refund model)
    currency            varchar(3)                               -- legacy; nullable (no longer in Refund model)
);

-- Idempotent migration for pre-existing volumes: relax NOT NULL on the dropped columns.
ALTER TABLE refund ALTER COLUMN transaction_id DROP NOT NULL;
ALTER TABLE refund ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE refund ALTER COLUMN currency DROP NOT NULL;

-- Payout: a payout issued against a payment order.
-- Model shape is {id, payment_order_id, created_at}; transaction_id/amount/currency are
-- legacy columns from an earlier shape, kept (nullable) so existing rows aren't lost.
CREATE TABLE IF NOT EXISTS payout (
    id                  bigint      PRIMARY KEY,                 -- snowflake id, set by app on insert
    payment_order_id    text        NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    transaction_id      bigint      REFERENCES transaction (id), -- legacy; nullable (no longer in Payout model)
    amount              integer,                                 -- legacy; nullable (no longer in Payout model)
    currency            varchar(3)                               -- legacy; nullable (no longer in Payout model)
);

-- Idempotent migration for pre-existing volumes: relax NOT NULL on the dropped columns.
ALTER TABLE payout ALTER COLUMN transaction_id DROP NOT NULL;
ALTER TABLE payout ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE payout ALTER COLUMN currency DROP NOT NULL;

-- PayoutReadiness: readiness signal for a payment order's payout (payin done + fulfilled).
CREATE TABLE IF NOT EXISTS payout_readiness (
    id                  bigint      PRIMARY KEY,                 -- snowflake id, set by app on insert (model comment: snowflake id; primary key)
    payment_order_id    text        NOT NULL,                    -- snowflake id (string-typed); indexed below (model comment: add an index)
    payin_complete      boolean     NOT NULL,
    fufilled            boolean     NOT NULL,                    -- spelling matches the model field
    created_at          text        NOT NULL                    -- string-typed in the model, no datetime directive -> text
);

CREATE INDEX IF NOT EXISTS payout_readiness_payment_order_id_idx ON payout_readiness (payment_order_id);
