// Generated by "Add database". Runs once on first init of notification-db.
// Schema authored from the model bank (model: Notification).
//
// Notification
//   id      string  -> primary key (unique index on `id`)
//   to      string  -> indexed
//   from    string
//   message string
//   sentAt  string

db = db.getSiblingDB('notification_db');

// --- Notification collection ---
if (!db.getCollectionNames().includes('Notification')) {
  db.createCollection('Notification', {
    validator: {
      $jsonSchema: {
        bsonType: 'object',
        required: ['id', 'to', 'from', 'message', 'sentAt'],
        properties: {
          id: { bsonType: 'string', description: 'primary key' },
          to: { bsonType: 'string', description: 'indexed' },
          from: { bsonType: 'string' },
          message: { bsonType: 'string' },
          sentAt: { bsonType: 'string' }
        }
      }
    }
  });
}

// primary key: unique index on `id`
db.Notification.createIndex({ id: 1 }, { unique: true, name: 'pk_id' });
// `to` => add index
db.Notification.createIndex({ to: 1 }, { name: 'idx_to' });
