-- Generated by "Add database". Runs once on first init of user-db.
-- Schema authored from model bank: User.

-- User: "id => primary key, snowflake id" (snowflake -> bigint)
CREATE TABLE IF NOT EXISTS "user" (
  id bigint PRIMARY KEY
);
