-- Generated by "Add database". Runs once on first init of chat-db.
-- Schema authored from model bank: Chat, Message

-- Chat: id => primary key, snowflake id; user_id => indexed; updated_at/created_at => insert time
CREATE TABLE IF NOT EXISTS chat (
    id          bigint PRIMARY KEY,
    user_id     bigint NOT NULL,
    title       text NOT NULL,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_user_id ON chat (user_id);

-- Message: id => primary key, snowflake id; chat => FK to chat (indexed); created_at => insert time
CREATE TABLE IF NOT EXISTS message (
    id          bigint PRIMARY KEY,
    chat_id     bigint NOT NULL REFERENCES chat(id),
    content     text NOT NULL,
    role        text NOT NULL CHECK (role IN ('user', 'assistant')),
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_message_chat_id ON message (chat_id);
