// WebSocket relay server — generated by "Add WebSockets".
//
// Identity and wiring come entirely from compose environment (SERVER_ID, WS_PORT,
// METRICS_PORT, BUS_REDIS_URL, PRESENCE_REDIS_URL, HEARTBEAT_MS, PRESENCE_TTL_S),
// so every server in the tier runs this same file.
//
// Message envelope (routed verbatim so receivers can dedupe and measure):
//   { msgId, from, to, body, sentAt }
//
// Routing: a client frame names a target clientId. If the target is connected HERE
// it's delivered directly; otherwise the presence cache says which server holds it
// and the message hops the pub/sub bus on that server's dedicated channel
// (`server:<id>`). Recipient unknown/offline -> dropped (barebones, by design).
import fs from 'node:fs'
import http from 'node:http'
import os from 'node:os'
import { pathToFileURL } from 'node:url'
import { WebSocketServer, WebSocket } from 'ws'
import Redis from 'ioredis'
import promClient from 'prom-client'

const SERVER_ID = process.env.SERVER_ID || os.hostname()
const WS_PORT = Number(process.env.WS_PORT || 8080)
const METRICS_PORT = Number(process.env.METRICS_PORT || 9100)
const HEARTBEAT_MS = Number(process.env.HEARTBEAT_MS || 30000)
const PRESENCE_TTL_S = Number(process.env.PRESENCE_TTL_S || 60)

// Two bus connections: a subscribed ioredis connection can't issue other commands,
// so publishes ride their own connection. Presence is a separate redis entirely.
const sub = new Redis(process.env.BUS_REDIS_URL)
const pub = new Redis(process.env.BUS_REDIS_URL)
const presence = new Redis(process.env.PRESENCE_REDIS_URL)
// ioredis reconnects on its own; a transient connect error must not crash the relay
// (an unhandled 'error' event / rejected presence command would take the process down
// mid-connections). The compose `restart: unless-stopped` covers a hard-dead redis.
for (const r of [sub, pub, presence]) r.on('error', () => {})

// --- Prometheus (scraped at :METRICS_PORT/metrics; the manifest node's PromQL
// reads these exact names — keep them if you customize this server) ---
const registry = new promClient.Registry()
promClient.collectDefaultMetrics({ register: registry })
const mConn = new promClient.Gauge({
  name: 'ws_connections', help: 'open websocket connections on this server', registers: [registry],
})
const mRecv = new promClient.Counter({
  name: 'ws_messages_received_total', help: 'frames received from clients', registers: [registry],
})
const mLocal = new promClient.Counter({
  name: 'ws_messages_delivered_local_total', help: 'messages delivered to a locally-connected client', registers: [registry],
})
const mRemote = new promClient.Counter({
  name: 'ws_messages_routed_remote_total', help: 'messages published to another server via the bus', registers: [registry],
})
const mDropped = new promClient.Counter({
  name: 'ws_messages_dropped_total', help: 'messages dropped (recipient offline or unknown)', registers: [registry],
})
const mLatency = new promClient.Histogram({
  name: 'ws_delivery_seconds', help: 'sender sentAt -> local delivery',
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1], registers: [registry],
})
http
  .createServer(async (req, res) => {
    if (req.url !== '/metrics') { res.writeHead(404); return res.end() }
    res.writeHead(200, { 'Content-Type': registry.contentType })
    res.end(await registry.metrics())
  })
  .listen(METRICS_PORT)

const localMap = new Map() // clientId -> ws connection (this server only)
const wss = new WebSocketServer({ port: WS_PORT })

// --- Bus: this server listens on its own dedicated channel. Routing already
// happened on the sending server; just deliver locally. ---
sub.subscribe(`server:${SERVER_ID}`).catch(() => {}) // retried by ioredis on reconnect
sub.on('message', (_channel, raw) => {
  const { targetClientId, payload } = JSON.parse(raw)
  deliverLocal(targetClientId, payload)
})

// --- Local delivery primitive ---
function deliverLocal(clientId, payload) {
  const conn = localMap.get(clientId)
  if (conn && conn.readyState === WebSocket.OPEN) {
    conn.send(JSON.stringify(payload))
    mLocal.inc()
    if (payload && typeof payload.sentAt === 'number') {
      mLatency.observe(Math.max(0, (Date.now() - payload.sentAt) / 1000))
    }
    fireHook('onSend', clientId, payload, hookCtx)
  } else {
    mDropped.inc()
  }
}

// --- Routing: local vs remote ---
async function route(targetClientId, payload) {
  if (localMap.has(targetClientId)) return deliverLocal(targetClientId, payload)
  let serverId = null
  try {
    serverId = await presence.get(`presence:${targetClientId}`)
  } catch {
    /* presence unreachable — treat as offline */
  }
  if (serverId) {
    pub.publish(`server:${serverId}`, JSON.stringify({ targetClientId, payload })).catch(() => {})
    mRemote.inc()
  } else {
    mDropped.inc() // recipient offline — barebones: drop
  }
}

// --- Shared additive hooks (mounted read-only at /app/shared/hooks.js) ---
// Fire-and-forget side effects layered on the fixed base relay above: onMessage
// (frame received from a client) and onSend (payload delivered to a client). A
// missing or broken hooks file must never take the relay down — tolerate absence,
// catch import errors, and log; the base path runs unconditionally either way.
const HOOKS_PATH = process.env.HOOKS_PATH || '/app/shared/hooks.js'
let hooks = null
if (fs.existsSync(HOOKS_PATH)) {
  try {
    hooks = (await import(pathToFileURL(HOOKS_PATH).href)).default ?? null
  } catch (err) {
    console.error(`hooks: failed to load ${HOOKS_PATH}: ${err.message}`)
  }
}
function fireHook(name, ...args) {
  const fn = hooks?.[name]
  if (typeof fn !== 'function') return
  try {
    Promise.resolve(fn(...args)).catch((err) => console.error(`hooks.${name}: ${err.message}`))
  } catch (err) {
    console.error(`hooks.${name}: ${err.message}`)
  }
}
const hookCtx = { serverId: SERVER_ID, localMap, presence, pub, deliverLocal, route }

// --- Connection lifecycle ---
wss.on('connection', (ws, req) => {
  const clientId = new URL(req.url, 'http://x').searchParams.get('clientId')
  if (!clientId) return ws.close(4000, 'clientId required')

  localMap.set(clientId, ws)
  mConn.set(localMap.size)
  presence.set(`presence:${clientId}`, SERVER_ID, 'EX', PRESENCE_TTL_S).catch(() => {})

  ws.isAlive = true
  // pong marks liveness AND refreshes the presence TTL backstop.
  ws.on('pong', () => {
    ws.isAlive = true
    presence.expire(`presence:${clientId}`, PRESENCE_TTL_S).catch(() => {})
  })

  // client frame arrives -> routing stage
  ws.on('message', (data) => {
    mRecv.inc()
    try {
      const msg = JSON.parse(data)
      route(msg.to, msg)
      fireHook('onMessage', msg, { ...hookCtx, clientId })
    } catch {
      /* ignore malformed frames */
    }
  })

  ws.on('close', () => {
    // A reconnect may have already replaced this entry — only clean up our own.
    if (localMap.get(clientId) === ws) {
      localMap.delete(clientId)
      mConn.set(localMap.size)
      presence.del(`presence:${clientId}`).catch(() => {})
    }
  })

  ws.on('error', () => ws.terminate())
})

// --- Server-side heartbeat: ping every HEARTBEAT_MS, terminate dead clients ---
setInterval(() => {
  wss.clients.forEach((ws) => {
    if (ws.isAlive === false) return ws.terminate()
    ws.isAlive = false
    ws.ping()
  })
}, HEARTBEAT_MS)
