-- Generated by "Add database". Runs once on first init of order-db.
-- Schema authored from model bank: Order, Item, OrderPayment, OrderItem.

-- Order: "// id => primary key" (string -> text)
CREATE TABLE IF NOT EXISTS "order" (
  id text PRIMARY KEY
);

-- Item: "// id => primary key", "// price => integer", "// currency => max length of 3"
CREATE TABLE IF NOT EXISTS item (
  id        text PRIMARY KEY,
  seller_id text NOT NULL,
  price     integer NOT NULL,
  currency  varchar(3) NOT NULL
);

-- OrderPayment:
--   "// id => primary key; composite of order.id and attempt_idx"
--   "// unique on (order, attempt_idx)"
--   "// order => foreign key to Order; put index on column"
--   "// seller_id => set from the seller_id of the Items belonging to the Order (uniform across the order's items)"
--   "// amount => integer; sum of the order's Item prices, same value sent in PaymentRegistrationRequest"
--   "// currency => max length of 3 characters; from the order's Items (uniform), same value sent in PaymentRegistrationRequest"
--   "// created_at => set at first insertion time"
--   status union -> CHECK constraint; token? optional -> nullable
CREATE TABLE IF NOT EXISTS order_payment (
  id          text PRIMARY KEY,
  order_id    text NOT NULL REFERENCES "order"(id),
  seller_id   text NOT NULL,
  amount      integer NOT NULL,
  currency    varchar(3) NOT NULL,
  attempt_idx numeric NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  status      text NOT NULL CHECK (status IN (
                'pending',
                'register_success',
                'register_fail',
                'payment_success',
                'payment_fail'
              )),
  token       text,
  UNIQUE (order_id, attempt_idx)
);
-- Additive migration guards: pick up new columns on a pre-existing order_payment volume.
ALTER TABLE order_payment ADD COLUMN IF NOT EXISTS seller_id text NOT NULL;
ALTER TABLE order_payment ADD COLUMN IF NOT EXISTS amount integer NOT NULL;
ALTER TABLE order_payment ADD COLUMN IF NOT EXISTS currency varchar(3) NOT NULL;

-- "// order => ... put index on column"
CREATE INDEX IF NOT EXISTS order_payment_order_id_idx ON order_payment (order_id);

-- OrderItem: "// many to many between Orders and Items"
-- join table; both fields are FKs; composite PK prevents duplicate links
CREATE TABLE IF NOT EXISTS order_item (
  order_id text NOT NULL REFERENCES "order"(id),
  item_id  text NOT NULL REFERENCES item(id),
  PRIMARY KEY (order_id, item_id)
);
