"""Stdlib-only load-balancer client for sandbox client scripts.

A client script (systems/<id>/clients/<client>.py) imports `lb` from here and calls
`lb.get/post/put/patch/delete("/<service>/<path>", body)` to make REAL HTTP calls through
the system's load balancer (http://localhost:8080). Every call is recorded; when the
process exits, the recorded calls are printed as one sentinel-delimited JSON line so the
web app's runner can show them in the Functions Run panel.

Uses only the Python standard library (urllib) so a client script runs on the host with no
`pip install`. Do not edit this file from a client script's authoring session — it is shared
by every client in the system.

A STATEFUL client (its manifest node has stateful:true) also imports `state` from here to
persist data across runs — see the _State docstring below. A stateless client can import it
too, but its `state` is an in-memory scratchpad discarded at exit.
"""
import atexit
import json
import os
import time
import urllib.error
import urllib.request

BASE = "http://localhost:8080"
RESULT_SENTINEL = "__LB_RESULTS__"
_MAX_TEXT = 2000

# Every call this process makes, in order — emitted at exit for the web app to render.
_calls = []


def _compact(response):
    # A history entry keeps the call's response, but a long text body is truncated the same way
    # _request truncates a non-JSON body — parsed dict/list responses are kept as-is (bounded data).
    if isinstance(response, str) and len(response) > _MAX_TEXT:
        return response[:_MAX_TEXT] + "…"
    return response


class _State:
    """A stateful client's durable key/value store + rolling call history.

    Persistence is enabled ONLY when the runner sets the LB_CLIENT_STATE env var to a file path
    (which it does when the client's manifest node is stateful). When enabled (`state.durable`),
    the store is loaded from that file at import and saved back at exit, so a later run reads what
    an earlier run saved — the client "remembers" outcomes across runs, like a websocket session:

        token = state.get("token")               # value an earlier run saved (None the first time)
        if not token:
            r = lb.post("/auth/login", {...})
            token = r["token"]
            state.set("token", token)            # persisted for the next run

    When disabled (a stateless client — no LB_CLIENT_STATE), it's an in-memory scratchpad:
    get()/set() work for THIS run only and nothing is written to disk.

    Every lb.* call's outcome is also auto-appended to `history` (when durable), so a stateful
    client accumulates the results of its API calls with no extra code.
    """

    _HISTORY_CAP = 200

    def __init__(self, path):
        self.durable = bool(path)
        self._path = path
        self._values = {}
        self._history = []
        if self.durable and os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
            except (OSError, ValueError):
                data = None
            if isinstance(data, dict):
                if isinstance(data.get("values"), dict):
                    self._values = data["values"]
                if isinstance(data.get("history"), list):
                    self._history = data["history"][-self._HISTORY_CAP:]

    def get(self, key, default=None):
        return self._values.get(key, default)

    def set(self, key, value):
        self._values[key] = value
        return value

    def all(self):
        return dict(self._values)

    def _append_history(self, entry):
        self._history.append(entry)
        if len(self._history) > self._HISTORY_CAP:
            del self._history[: len(self._history) - self._HISTORY_CAP]

    def _save(self):
        # Best-effort + atomic (write a temp then os.replace). Fully guarded so a write error can
        # never raise out of atexit — an escaping atexit exception prints a traceback and can flip
        # the exit code, which the runner would surface as a spurious script error.
        try:
            tmp = self._path + ".tmp"
            with open(tmp, "w", encoding="utf-8") as f:
                json.dump({"values": self._values, "history": self._history}, f, indent=2)
                f.write("\n")
            os.replace(tmp, self._path)
        except Exception:
            pass


# The durable store for a stateful run, or an in-memory scratchpad otherwise. LB_CLIENT_STATE is
# set by the runner (scenarios.js / an end-to-end orchestrator) only for a stateful client node.
state = _State(os.environ.get("LB_CLIENT_STATE"))


def _record(method, path, sent_body, status, ok, response):
    _calls.append(
        {
            "method": method,
            "path": path,
            "sentBody": sent_body,
            "status": status,
            "ok": ok,
            "response": response,
        }
    )
    # A stateful client accumulates the outcome of every call in its durable history. The
    # stateless path (state.durable is False) does no extra work — behavior unchanged.
    if state.durable:
        state._append_history(
            {
                "method": method,
                "path": path,
                "status": status,
                "ok": ok,
                "response": _compact(response),
                "at": time.time(),
            }
        )


def _request(method, path, body=None):
    url = BASE + path
    data = None
    headers = {}
    if body is not None and method not in ("GET", "HEAD"):
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            status = resp.status
            raw = resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as err:
        # A 4xx/5xx is still a real response the script may want to branch on — record it.
        status = err.code
        raw = err.read().decode("utf-8", "replace")
    except Exception as err:  # connection refused, DNS, timeout, …
        _record(method, path, body, 0, False, None)
        raise RuntimeError("%s %s failed: %s" % (method, path, err))
    try:
        parsed = json.loads(raw)
    except ValueError:
        parsed = raw if len(raw) <= _MAX_TEXT else raw[:_MAX_TEXT] + "…"
    ok = 200 <= status < 400
    _record(method, path, body, status, ok, parsed)
    return parsed


def _parse_frame(text):
    # An SSE event's `data:` payload — JSON when it is, else the raw text (truncated like _request).
    try:
        return json.loads(text)
    except ValueError:
        return text if len(text) <= _MAX_TEXT else text[:_MAX_TEXT] + "…"


def _stream(path, max_events, timeout):
    """Consume a Server-Sent Events (text/event-stream) GET through the lb, incrementally.

    An SSE route streams until the client goes away, so this is BOUNDED: it stops after
    `max_events` events OR `timeout` seconds (whichever comes first), and an idle stream unblocks
    on the socket read timeout. It must terminate well within the runner's 30s budget, because the
    recorded calls are only emitted when this process exits. Records ONE call whose `response` is
    the list of collected `data:` payloads (each JSON-parsed when possible) and returns that list.
    """
    url = BASE + path
    req = urllib.request.Request(
        url, method="GET", headers={"Accept": "text/event-stream"}
    )
    frames = []
    try:
        # `timeout` doubles as the per-read socket timeout, so a silent stream can't block forever.
        resp = urllib.request.urlopen(req, timeout=timeout)
    except urllib.error.HTTPError as err:
        # A 4xx/5xx is a real response the script may branch on — record it like _request does.
        body = err.read().decode("utf-8", "replace")
        _record("GET", path, None, err.code, False, _parse_frame(body))
        return frames
    except Exception as err:  # connection refused, DNS, connect timeout, …
        _record("GET", path, None, 0, False, None)
        raise RuntimeError("GET %s (stream) failed: %s" % (path, err))

    status = resp.status
    deadline = time.monotonic() + timeout
    data_lines = []
    try:
        for raw_line in resp:  # HTTPResponse yields chunked-decoded lines
            line = raw_line.decode("utf-8", "replace").rstrip("\r\n")
            if line == "":  # a blank line terminates one event
                if data_lines:
                    frames.append(_parse_frame("\n".join(data_lines)))
                    data_lines = []
            elif line.startswith(":"):
                pass  # SSE comment / heartbeat — ignore
            elif line.startswith("data:"):
                data_lines.append(line[5:].lstrip(" "))
            # other fields (event:/id:/retry:) don't contribute to the recorded payload
            if len(frames) >= max_events or time.monotonic() >= deadline:
                break
    except Exception:
        # A read timeout on an idle stream (or a mid-stream drop) just ends collection — keep
        # whatever frames we already have rather than losing the whole call.
        pass
    finally:
        try:
            resp.close()
        except Exception:
            pass
    if data_lines and len(frames) < max_events:  # flush a trailing unterminated event
        frames.append(_parse_frame("\n".join(data_lines)))

    ok = 200 <= status < 400
    _record("GET", path, None, status, ok, frames)
    return frames


class _LB:
    """The `lb` object a client script uses to call the system through the load balancer.

    Each method returns the parsed JSON response body (a dict/list), or the raw text if the
    response wasn't JSON — so a script can chain one call's result into the next:

        r = lb.post("/orders-service/orders/checkout", {"order_id": order_id})
        if r.get("status") == "valid":
            lb.post("/payments-api/complete-payment", {"token": r["token"]})

    `lb.stream(path)` consumes a Server-Sent Events (text/event-stream) endpoint instead and
    returns the list of `data:` payloads it collected (bounded — see stream()).
    """

    def get(self, path):
        return _request("GET", path)

    def post(self, path, body=None):
        return _request("POST", path, body)

    def put(self, path, body=None):
        return _request("PUT", path, body)

    def patch(self, path, body=None):
        return _request("PATCH", path, body)

    def delete(self, path, body=None):
        return _request("DELETE", path, body)

    def stream(self, path, max_events=20, timeout=5.0):
        # Consume an SSE (text/event-stream) GET; returns the collected list of `data:` payloads.
        # Bounded by max_events / timeout so the run always completes (see _stream).
        return _stream(path, max_events, timeout)


lb = _LB()


@atexit.register
def _emit():
    # One line the runner can find amid the script's own output. Runs on normal exit AND
    # after an unhandled exception, so a partially-completed run still reports its calls.
    print(RESULT_SENTINEL + " " + json.dumps(_calls))


# For a stateful client, persist the store back to disk at exit. Registered AFTER _emit, so atexit's
# LIFO order runs the save first, then the sentinel print — both fire on normal exit and after an
# unhandled exception. (A timeout kill sends SIGTERM, which skips atexit entirely, so a timed-out
# run persists nothing — the same way it already reports no __LB_RESULTS__.)
if state.durable:
    atexit.register(state._save)
