"""Stdlib-only load-balancer client for sandbox client scripts.

A client script (systems/<id>/clients/<client>.py) imports `lb` from here and calls
`lb.get/post/put/patch/delete("/<service>/<path>", body)` to make REAL HTTP calls through
the system's load balancer (http://localhost:8080). Every call is recorded; when the
process exits, the recorded calls are printed as one sentinel-delimited JSON line so the
web app's runner can show them in the Functions Run panel.

Uses only the Python standard library (urllib) so a client script runs on the host with no
`pip install`. Do not edit this file from a client script's authoring session — it is shared
by every client in the system.
"""
import atexit
import json
import urllib.error
import urllib.request

BASE = "http://localhost:8080"
RESULT_SENTINEL = "__LB_RESULTS__"
_MAX_TEXT = 2000

# Every call this process makes, in order — emitted at exit for the web app to render.
_calls = []


def _record(method, path, sent_body, status, ok, response):
    _calls.append(
        {
            "method": method,
            "path": path,
            "sentBody": sent_body,
            "status": status,
            "ok": ok,
            "response": response,
        }
    )


def _request(method, path, body=None):
    url = BASE + path
    data = None
    headers = {}
    if body is not None and method not in ("GET", "HEAD"):
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            status = resp.status
            raw = resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as err:
        # A 4xx/5xx is still a real response the script may want to branch on — record it.
        status = err.code
        raw = err.read().decode("utf-8", "replace")
    except Exception as err:  # connection refused, DNS, timeout, …
        _record(method, path, body, 0, False, None)
        raise RuntimeError("%s %s failed: %s" % (method, path, err))
    try:
        parsed = json.loads(raw)
    except ValueError:
        parsed = raw if len(raw) <= _MAX_TEXT else raw[:_MAX_TEXT] + "…"
    ok = 200 <= status < 400
    _record(method, path, body, status, ok, parsed)
    return parsed


class _LB:
    """The `lb` object a client script uses to call the system through the load balancer.

    Each method returns the parsed JSON response body (a dict/list), or the raw text if the
    response wasn't JSON — so a script can chain one call's result into the next:

        r = lb.post("/orders-service/orders/checkout", {"order_id": order_id})
        if r.get("status") == "valid":
            lb.post("/payments-api/complete-payment", {"token": r["token"]})
    """

    def get(self, path):
        return _request("GET", path)

    def post(self, path, body=None):
        return _request("POST", path, body)

    def put(self, path, body=None):
        return _request("PUT", path, body)

    def patch(self, path, body=None):
        return _request("PATCH", path, body)

    def delete(self, path, body=None):
        return _request("DELETE", path, body)


lb = _LB()


@atexit.register
def _emit():
    # One line the runner can find amid the script's own output. Runs on normal exit AND
    # after an unhandled exception, so a partially-completed run still reports its calls.
    print(RESULT_SENTINEL + " " + json.dumps(_calls))
